### ISSUE TITLE
Native name for "fa" locale missing in "en" (but is present in "fa")

### ISSUE THREAD

**Issue by arouinfar** [phetsims/website#310] opened 2015-11-13 07:51 UTC
After submitting the the Persian translation of Hooke's Law, I noticed the native name of the locale (فارسی) is not being properly recorded in the Translations table. 
<img width="612" alt="screen shot 2015-11-13 at 12 25 48 am" src="https://cloud.githubusercontent.com/assets/8419308/11140937/553dd5de-899d-11e5-8dea-8d08981b16d9.png">

This is inconsistent with other places on the site. For example, the Persian translation of the site is appropriately listed as "فارسی" in the footer. The list of all sims in Persian (http://phet.colorado.edu/fa/simulations/translated/fa) also shows "(فارسی) Persian", so I'm not sure why the English version does not list فارسی as the native name for the fa locale.

<img width="814" alt="screen shot 2015-11-13 at 12 23 35 am" src="https://cloud.githubusercontent.com/assets/8419308/11141057/b188bab0-899e-11e5-911d-2d348a7b98b0.png">

**Comment by aaronsamuel137** [comment] 2015-11-16 17:00
This issue is caused by using the default Java Locale display name, which apparently doesn't exist for Persian.

The fix involves falling back to our translation for the string if it is not found in the Java code.

I've implemented this, but I think we should spot check on phet-dev a bit to make sure that everything else still looks correct.

Assigning to @arouinfar for review. (Take a look at some other translation sections to make sure nothing else got broken)

**Comment by arouinfar** [comment] 2015-11-16 18:51
Thanks for looking into this issue @aaronsamuel137.

I found two other places that could use the fallback solution. Other than that, everything else looks good.

http://phet-dev.colorado.edu/en/simulations/translated/fa
The title of the table should read: فارسی (Persian)
![image](https://cloud.githubusercontent.com/assets/8419308/11190224/c5bded74-8c51-11e5-9651-7cd2cc7655e3.png)

http://phet-dev.colorado.edu/en/simulations/translated
فارسی is also missing from the "Translated Sims" table 
![image](https://cloud.githubusercontent.com/assets/8419308/11190274/f337e2be-8c51-11e5-954e-e06663bea6d2.png)

**Comment by aaronsamuel137** [comment] 2015-11-16 22:45
I've made these changes, anything else to do here?

Assigning to @arouinfar for review.

**Comment by arouinfar** [comment] 2015-11-16 23:16
@aaronsamuel137, the Translated Sims page and the sim pages look good. However, it looks like something on the /simulations/translated/[locale] pages is broken. (e.g. http://phet.colorado.edu/en/simulations/translated/es) 

The pages that lists all of the sims in a given locale should be titled: Native name of locale (Name of language in website's locale)

For example, the list of sims in Spanish should read: Español (Spanish) 
http://phet.colorado.edu/en/simulations/translated/es
![image](https://cloud.githubusercontent.com/assets/8419308/11197546/5c993284-8c7b-11e5-923d-f23a37c3ace7.png)

On phet-dev, the native name of the locale is repeated twice.
http://phet-dev.colorado.edu/en/simulations/translated/es
![image](https://cloud.githubusercontent.com/assets/8419308/11197555/67683fac-8c7b-11e5-9a94-b2fcc6da4753.png)


I think you may have swapped the pattern. Looking at the list of sims in Persian, the title reads "Persian (فارسی)" instead of "فارسی (Persian)".
http://phet-dev.colorado.edu/en/simulations/translated/fa
![image](https://cloud.githubusercontent.com/assets/8419308/11197660/2527f3a2-8c7c-11e5-90cb-1ab4ca2e1fec.png)

**Comment by aaronsamuel137** [comment] 2015-11-17 00:14
Good catch, I did swap the pattern. Should be fixed now on phet-dev (you might need to hard refresh). I'll plan on deploying this on Wednesday unless you see any other issues.

**Comment by arouinfar** [comment] 2015-11-17 00:31
Looks good on my end! Thanks @aaronsamuel137.

**Comment by arouinfar** [comment] 2015-11-18 18:47
Reassigning to @aaronsamuel137 for redeploy.

**Comment by aaronsamuel137** [comment] 2015-11-20 05:16
Deployed to figaro. Closing

**Closed by aaronsamuel137** 2015-11-20 05:16 UTC
