### ISSUE TITLE
Add a resend option for confirmation emails

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#361] opened 2016-01-06 22:41 UTC
Currently, if a user changes their email, they get a message saying an email has been sent. However, if a user never gets this email, they must email phethelp. Instead, we would like users to be able to resend a confirmation email. The page would look like this: 

<img width="447" alt="screen shot 2016-01-06 at 3 42 56 pm" src="https://cloud.githubusercontent.com/assets/7852916/12157033/0490a2c8-b48c-11e5-9711-0e5b452b68c5.png">

**Comment by mattpen** [comment] 2016-01-13 23:19
I discussed this with @oliver-phet today. This function currently exists on the Login popup panel.  I can add a button that does the same thing on the "Awaiting Email Confirmation" page.  

One thing that I noticed is that if a user tries to login without confirming their email they get a message that states 
> An invalid email address and/or password has been entered.

Should we improve this?   My suggestion would be that if a user tries to logon and they have registered but not confirmed their email they get a message that reads something like 

> You have not yet confirmed your email address.  Please {click here} to resend the confirmation email.  If you have tried this multiple times and have not received the email, please add phethelp@gmail.com to your whitelist.  If you still do not receive the email then send a message to phethelp@gmail.com directly.

**Comment by amanda-phet** [comment] 2016-01-13 23:26
>This function currently exists on the Login popup panel.  

This is relatively new because we had this discussion recently and no one mentioned this. I also know it was not part of the original design of that panel (which now needs some redesigning... there are too many scattered links). 

If it's possible to know that the user's email is invalid *because they have not yet confirmed*, then your message sounds great. I assume it is a generic message because the server does not verify exactly why the email address is invalid.

**Comment by oliver-phet** [comment] 2016-01-13 23:30
I mentioned that the 'Resend' function already exists... but only on the login popup. I think it should be added to the "Awaiting Email Confirmation" page.

Users can get to this page three ways (that I can think of):
1. Just completed registration
2. Just changed email address
3. Attempt to login with an unconfirmed email

**Comment by oliver-phet** [comment] 2016-01-13 23:34
Maybe the only change to @amanda-phet 's original design would be to add a line about whitelisting: 

*If you do not receive the confirmation email, please add phethelp@gmail.com to your whitelist.*

**Comment by mattpen** [comment] 2016-01-13 23:35
> 3. Attempt to login with an unconfirmed email

This currently isn't implemented.  I think it should be possible, I can take a stab at it tonight.  Personally, I like this solution better than my suggestion above.

**Comment by kathy-phet** [comment] 2016-01-14 04:51
Just quick note. It should be email phethelp@colorado.edu<mailto:phethelp@colorado.edu>.

We should not have the gmail address public anywhere on the website or in messages we send.

Hope all is well at the Homefront!
K

Sent from my iPhone

On Jan 13, 2016, at 3:34 PM, Oliver Nix <notifications@github.com<mailto:notifications@github.com>> wrote:


Maybe the only change to @amanda-phet<https://github.com/amanda-phet> 's original design would be to add a line about whitelisting:

If you do not receive the confirmation email, please add phethelp@gmail.com<mailto:phethelp@gmail.com> to your whitelist.

-

**Comment by mattpen** [comment] 2016-01-15 01:46
I changed all instances of phethelp@gmail to phethelp@colorado

@amanda-phet and @oliver-phet  I've posted a working draft of this change on phet-dev.  Can please check it out and see if it is working as intended?

@ariel-phet - This required a significant change to the login procedure.  It would probably be good to have Steele or someone test out all the edge/corner use cases.  I've tested the cases its intended for and I'll continue to test further, but I certainly haven't been exhaustive.

**Comment by oliver-phet** [comment] 2016-01-15 16:12
A few things I noticed:
1. https://phet-dev.colorado.edu/en/resend-email-confirmation This page has the title "Reset Your Password" it should be "Resend Email Confirmation"
2. On the 'Awaiting Email Confirmation' page:
- Resend should be a blue button (centered)
- put the "If you do not receive the confirmation email, please add phethelp@colorado.edu to your whitelist." below the Resend button (br between this text and button). Not italics font.

**Comment by mattpen** [comment] 2016-01-15 19:11
1. This appears to have fixed itself.  I'm not sure what happened here.   The title is now "Awaiting Email Confirmation".  We can change it by changing the translatable string "newsletter.confirmEmailSent.title"
2. (a) - This should be fixed now too, it was not showing up because the old CSS was cached by varnish.
2 (b) - I fixed this today and it is live on phet-dev now.

**Comment by oliver-phet** [comment] 2016-01-15 19:22
Looks good, but the Resend button doesn't look centered? I'm guessing it is just due to the length of the text above the button?
<img width="1280" alt="screen shot 2016-01-15 at 12 20 16 pm" src="https://cloud.githubusercontent.com/assets/5090275/12362786/69644a2c-bb82-11e5-8fac-d87e7a1d8129.png">

**Comment by amanda-phet** [comment] 2016-01-15 20:21
Looking good! I would just request a little more white space below the resend button. 

@oliver-phet the button is centered in the body of the page, but since each line is short it doesn't appear centered. It's fine with me but if it bothers you then I'm fine if it gets changed.

**Comment by kathy-phet** [comment] 2016-01-16 04:38
Matt, I don't know what all the instances of phethelp@gmail were in
    the code. The ones that are/were important to change were the
    user-facing ones where the email was visible to the user/teacher. We
    want the project to be perceived as a University of Colorado Boulder
    project so that is why the user facing instances need to show phethelp@colorado.edu even
    though those automatically forward to phethelp@gmail for historic
    space reasons. 
    
    Not sure if there were none user-facing instances of phethelp@gmail
    that were changed that caused extra complication, but sorry if that
    is the case. I should have been clear about the reason. 
    
    Kathy 
    
    On 1/14/2016 6:46 PM, Matt Pennington
      wrote:
    
    
      
      I changed all instances of phethelp@gmail to phethelp@colorado
      @amanda-phet and @oliver-phet I've posted a working
        draft of this change on phet-dev. Can please check it out and
        see if it is working as intended?
      @ariel-phet - This required a
        significant change to the login procedure. It would probably be
        good to have Steele or someone test out all the edge/corner use
        cases. I've tested the cases its intended for and I'll continue
        to test further, but I certainly haven't been exhaustive.
      —
        Reply to this email directly or view

          it on GitHub.

**Comment by ariel-phet** [comment] 2016-01-16 06:07
@amanda-phet @oliver-phet @mattpen I would suggest either left aligning the Resend button or centering it under the last line of text above it. It looks a little buggy in this layout.

@mattpen please create a task for @phet-steele and assign it to me for prioritization.

**Comment by mattpen** [comment] 2016-01-19 15:19
@kathy-phet - There were never any instances of phethelp@gmail in a public facing location on the website in relation to this issue.  It was simply a typo in Github on my part.  Thanks for clarifying the reasoning!

**Comment by phet-steele** [comment] 2016-01-19 19:35
@mattpen, some of the logic to the Resend Email Confirmation page doesn't make sense (the page incorrectly showing Reset Your Password is what I'm talking about). It doesn't seem quite like it works when trying to change an email address with an already existing account. Here's some steps:

1. Have an account with Email A, and go to edit your profile.
2. Scroll down to change your email address.
3. Type in Email B, your password, and submit it.
4. You'll be brought to the Awaiting Email Conformation page, and instead of confirming Email B, click the Resend button.
5. Re-typing the newly desired Email B into this field on the Resend Email Confirmation will return the error that Email B is not associated with a PhET account. Well of course it isn't, I'm trying to change it to that new email! The logic here seems wrong if I'm blocked from resending the confirmation email.

**Comment by mattpen** [comment] 2016-01-20 21:40
@amanda-phet @oliver-phet - In response to @phet-steele's comments I changed the page slightly.  If the page is reached in response to an email change request, there are now two fields, one for Current Email and one for New Email, I attached a screenshot below.  Does this sound reasonable?  I'll post to phet-dev shortly.

I also added behavior that will auto-fill the email address if the user entered it on the previous page, for example after registration or after submitting an email change request.
![image](https://cloud.githubusercontent.com/assets/11747676/12463486/f7bf5ad0-bf80-11e5-9c6d-728ba7d99b4b.png)

**Comment by mattpen** [comment] 2016-01-21 02:44
This was discussed at the 1/20/16 web design meeting with @amanda-phet @oliver-phet @amyh-phet @phet-steele @arouinfar.  We discovered a plethora of corner cases and there was some disagreement about how to best handle them.  I started a [process document](https://docs.google.com/document/d/1upfPYU_ahKsCjpuQ8UdwvTVfbRtr3SElVSXfUPCbb2E/edit?usp=sharing) to delineate the various use cases and the expected response.  

+ The numeric items represent the desired workflow.  
+ Sub-items (I.3.a for example) represent possible deviations from the ideal path and are in no particular order.  
+ Items highlighted in yellow are in need of discussion or decision.  

Please add or correct anything I missed or misunderstood!

**Comment by mattpen** [comment] 2016-01-21 05:23
I changed the behavior of the AwaitingEmailConfirmation page so it now redirects to itself.  This has been posted to phet-dev.

**Comment by mattpen** [comment] 2016-01-28 04:53
Tagging developer-meeting to follow up on email discussion with @ariel-phet and @oliver-phet.

**Comment by ariel-phet** [comment] 2016-01-28 05:02
@mattpen @oliver-phet 

There was a suggestion that perhaps we should also request multiple email addresses (for instance an alternative personal email address) - this suggestion came from Edmodo that has literally millions of teacher users.

**Comment by mattpen** [comment] 2016-01-28 19:47
We can delay dev-meeting discussion till next week.

**Comment by pixelzoom** [comment] 2016-02-02 17:22
2/2/16 dev meeting: This is a conversation that @mattpen needs to have with @oliver-phet.

**Comment by mattpen** [comment] 2016-02-11 23:35
@oliver-phet - The user is now directed to this page if they are logging in without a confirmed email, both in the case of a new user and in the case of a user who has submitted a password reset request.  I've published the change to phet-dev.  Is there anything else that needs to be done as part of this issue?  

(The secondary email will be handled as part of #379)

**Comment by oliver-phet** [comment] 2016-02-12 03:35
I just tested on phet-dev and it looks good. I think that is all for this issue now.

**Comment by mattpen** [comment] 2016-02-12 05:34
Great.  I'll go ahead and publish to figaro as long as nothing comes up in testing.

**Comment by mattpen** [comment] 2016-02-18 06:58
This was deployed to figaro tonight.  Closing.

**Closed by mattpen** 2016-02-18 06:58 UTC
Labels: website:addressed-waiting-deploy, website:user-accounts
