### ISSUE TITLE
New Offline Access page to replace current How to Run Simulations page(s)

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#306] opened 2015-11-09 21:54 UTC
As part of the new help center sub-project, we would like one page for offline sim access (instead of the current page that has a table and three sub-pages). The URL can be the same (https://phet.colorado.edu/en/get-phet), but there will be no sub-pages. Instead, we'd like three expandable sections for content. 
![screen shot 2015-11-09 at 2 50 22 pm](https://cloud.githubusercontent.com/assets/7852916/11047730/3f96df5e-86f1-11e5-858f-0aa50c3a0148.png)

The first section *Desktop/Laptop Computer* will have two sub-sections: Full Install (this should contain the same context that is on the current full install page.) and a One at a Time table. This table under will have all sims listed and offer potentially two different versions of a sim. These will be differentiated in the "Technology" column. 
![screen shot 2015-11-09 at 2 50 45 pm](https://cloud.githubusercontent.com/assets/7852916/11047741/4b51e4ec-86f1-11e5-983a-d4d13c92e153.png)

The second and third sections will only have One at a Time tables and they will vary slightly.  

The table under *Chromebook* will only list HTML5 sims.
![screen shot 2015-11-09 at 2 51 59 pm](https://cloud.githubusercontent.com/assets/7852916/11047774/74c90ab2-86f1-11e5-9e1c-26e54685ca69.png)

The table under *iPad* will have some special instructions about opening the sim in a browser and saving it to a reading list. The table will only list HTML5 sims AND will have a "run now" button instead of "download" because the sims will open in the browser. 
![screen shot 2015-11-09 at 2 52 13 pm](https://cloud.githubusercontent.com/assets/7852916/11047789/7d81ce0a-86f1-11e5-9c3e-c746eb13669a.png)

**Comment by mattpen** [comment] 2015-11-10 17:43
@amanda-phet As part of the new help center task #288 we are already adding an offline page.  However it is not currently separated by system type.  Would you like to have the systems separated like the accordion pictured here, or would it be better to use the additional navigation bar, like the screenshots for the RunningSims page (the image on the top right)? ![help-center-with-icons](https://cloud.githubusercontent.com/assets/3193912/10525670/3af05f6e-7343-11e5-8231-018cc1a71def.png)

**Comment by amanda-phet** [comment] 2015-11-10 18:20
The page for this issue should replace the current "How to Run Simulations" page found here: https://phet.colorado.edu/en/get-phet. The *Offline* page in the *Help Center* is for help questions relating to offline use. 

We considered using icons but since there are just three platforms I think the mockups above will work best.

**Comment by amanda-phet** [comment] 2015-11-10 18:22
I can see why this was confusing, so I added some details to the original issue above.

**Comment by aaronsamuel137** [comment] 2015-11-10 21:01
Feel free to work on this @mattpen. Not sure if I'll get to it or not before I leave.

**Comment by mattpen** [comment] 2015-12-02 17:38
@amanda-phet The first section, "Desktop/Laptop Computer", is up on phet-dev now.  http://phet-dev.colorado.edu/en/offline-access

**Comment by amanda-phet** [comment] 2015-12-02 17:46
It looks really great! 

I will work on the text for the iPad section since that sentence was just filler.

**Comment by mattpen** [comment] 2015-12-02 17:52
Ok, thanks!
I'll start work on the Chromebook section next.

**Comment by mattpen** [comment] 2015-12-04 15:57
@amanda-phet, the chromebook and ipad one-at-a-time tables are now up on phet-dev.

**Comment by amanda-phet** [comment] 2015-12-17 01:03
This is looking great. However, we want to make a change to the Desktop/Laptop table. Since it's a long table, users might appreciate being able to sort by technology type. So, we are thinking we should use the sortable table (the purple one that is on sim pages with activities listed) and make a column for each code base. 

This would be simple if you were using the purple table as it is, but something we've been wanting to add to that table are arrows to cue that it is sortable. So, this is a two-part request. 

1. Modify the purple activities table to have arrows next to the words (very similar to a Wikipedia table) that can be clicked to sort. The arrows will also indicate how the table is being sorted (in the case below, it is by sim name). 
2. Change the Desktop/Laptop table to be sortable and put the technology under the appropriate column. This means each row will have at least 1 empty column.  

<img width="770" alt="screen shot 2015-12-16 at 6 02 01 pm" src="https://cloud.githubusercontent.com/assets/7852916/11858463/1333d2b4-a41f-11e5-948f-c7ef031c9f1a.png">

Let me know if you have any questions or if this is unclear!

**Comment by mattpen** [comment] 2015-12-18 18:59
@amanda-phet - I've made these changes and posted them to phet-dev.  I left the chromebook/ipad tables as-is because they are smaller, but I can apply the same style/sortability pretty easily.

**Comment by amanda-phet** [comment] 2015-12-18 19:09
That came together really quickly! I don't think the other tables need to be sortable since they only contain HTML5 sims. 

One small tweak- can the double arrows show a down or up when being sorted? In the mockup, simulation name only has a down arrow because that is the default sort. It would change to up if clicked again, or another column would change to down if clicked.

**Comment by mattpen** [comment] 2015-12-22 04:10
@amanda-phet The tables now have dynamic sort icons.  This has been posted to phet-dev.

**Comment by amanda-phet** [comment] 2015-12-22 18:48
These seem to be working great! My only tweak would be to add some space between the word and the arrows. I'll see what the team thinks at tomorrow's meeting!

**Comment by ariel-phet** [comment] 2015-12-22 20:12
:+1: No question that more negative space is needed between the words and sort arrows, please increase it @mattpen

**Comment by mattpen** [comment] 2015-12-22 21:29
I added spacing before the icons.  This is now up on phet-dev.

**Comment by mattpen** [comment] 2015-12-24 20:36
As there was some confusion, I'm clarifying which of the in-progress website changes are dependent on each other.  
This change is dependent on the help-center being deployed.  It can be deployed after or at the same time as the help-center, but not before.

**Comment by amanda-phet** [comment] 2016-01-05 00:19
It would be nice to address #347 first, but if that is not possible then the minor tweaks for this page include: 
- [ ] remove the space after the icons in the chromebook and iPad tables
- [ ] make the row heights for the chromebook and iPad tables the same as the laptop table
- [ ] make the column titles for chromebook and iPad tables *not* bold 
- [ ] Add the following text under the iPad heading (subject to future edits, but we need something for now): To access a PhET simulation on an iPad while not connected to the internet, first open the sim in Safari by clicking the play button. Tap the Action button and then tap Add to Reading List. In the future, simply tap the Bookmarks icon and tap the sim page that is saved in the Reading List.

**Comment by mattpen** [comment] 2016-01-06 18:28
@amanda-phet -- Regarding "make the row heights for the chromebook and iPad tables the same as the laptop table", do you prefer the taller height or shorter?

**Comment by amanda-phet** [comment] 2016-01-06 18:31
The shorter height seems to be working well in the laptop table, so let's go with that.

**Comment by mattpen** [comment] 2016-01-25 20:50
@amanda-phet I've mixed in the new style of table in the offline-access page and added the additional requests from your comment above.  This was posted to phet-dev today.  Is there anything else we need to implement here?

**Comment by amanda-phet** [comment] 2016-01-27 21:24
It looks great. 

I would just make the download icon/technology spacing consistent. It looks good in the chromebook table (the icon and HTML5 text spaced apart and also aligned along the same horizontal center), so I'd do the same to the laptop/desktop table.

<img width="606" alt="screen shot 2016-01-27 at 2 23 27 pm" src="https://cloud.githubusercontent.com/assets/7852916/12628695/a2391908-c501-11e5-9431-486475bdc407.png">

**Comment by ariel-phet** [comment] 2016-01-27 21:56
One tweak I would make is that when I click technology I like how it sorts the first time, but the second time I click it took me a little while that it was doing reverse alphabetical order within the technology sort. I think this is unnecessary...I would just go with clicking "HTML5" sorts the html5 to the top with alphabetical order within that group, clicking again goes to unsorted (for each code base). That seemed to work well in the translated table when I used it, and I find the current interaction confusing.

@amanda-phet - do you agree?

**Comment by amanda-phet** [comment] 2016-01-27 22:00
I think that what this does is actually more standard than what we are doing in the translated sims table, but I agree that we should make it consistent since it is the same type of information.

**Comment by mattpen** [comment] 2016-01-29 19:01
@amanda-phet @ariel-phet Are we in agreement that the sorting should be like in the translated table?     Or is this still under discussion?

**Comment by amanda-phet** [comment] 2016-02-01 21:59
Yes, @ariel-phet and I would like the sorting to mimic what you've done with the code column in the translated table.

**Comment by mattpen** [comment] 2016-02-05 21:04
@amanda-phet @ariel-phet - The new sortable behavior is up on phet-dev.  Is this OK to deploy to figaro now?  

(Note: It will need to wait until after the helpcenter #288 is fully deployed)

**Comment by ariel-phet** [comment] 2016-02-17 22:07
Yes, looks good!

**Comment by mattpen** [comment] 2016-02-18 07:04
This was deployed to figaro tonight.

As of 12PM MST, about 30 minutes after the deploy, we were still receiving several requests for the old get-phet pages.  I can add a redirect if needed.

Tagging @jonathanolson so he is aware.

**Comment by jonathanolson** [comment] 2016-02-18 07:11
It's been my policy that if we are moving a page (roughly equivalent), it should have a redirection. If the content no longer exists (and there is no equivalent), a 404 is appropriate.

Currently https://phet.colorado.edu/en/get-phet is showing an internal server error. Redirection sounds best here, particularly so we can avoid having our server logs get filled.

**Comment by mattpen** [comment] 2016-02-21 05:55
@jonathanolson - The redirects are now live on phet-dev.  I'll test them on Monday and publish to figaro if all goes well.

**Comment by mattpen** [comment] 2016-02-23 06:59
@jonathanolson - The redirects for FAQ, get-phet and troubleshooting pages were deployed to figaro tonight and are working as designed.  This task appears to be complete, closing.

**Closed by mattpen** 2016-02-23 06:59 UTC
Labels: type:bug, website:help-center
