### ISSUE TITLE
Scrolling video player blanks out

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#125] opened 2015-04-15 18:37 UTC
Similar to #38, the video player on the front page is still having issues on Win 8.1 browsers.

![lonely wave](https://cloud.githubusercontent.com/assets/5863899/7165775/f852ffac-e366-11e4-94ed-59e9c5f54ca5.png)

I didn't have issues on Monday (4/13) but am seeing them now (4/15). I notice it most often when I start on a page other than the home page, then click the PhET logo to return home.
This video is one of the more extreme cases on IE11, it starts with the player not advancing nor the sim names displaying:
https://drive.google.com/file/d/0B3HJopSo_QqLdnhTN0c4M0hrT3c/view?usp=sharing

**Comment by aaronsamuel137** [comment] 2015-04-15 18:39
Can you open the javascript console next time you see this and let me know if there are any errors?

**Comment by phet-steele** [comment] 2015-04-15 19:36
I don't see any errors in the console, across all browsers.

**Comment by aaronsamuel137** [comment] 2015-04-15 22:04
A few more questions for you:

1. Does this happen only on phet-dev or on the main site too?
2. Did you get the video into a state where the player was not advancing and the names not displaying and then look at the console? I think the weird video playback is a different issue than the videos themselves getting funky.
3. What browsers does are these bugs reproducible on? I have never come across it before.

**Comment by phet-steele** [comment] 2015-04-17 17:31
1. Yes I see it on the main site.
2. No I haven't checked the console in the case of the player not advancing , I'll get on that.
3. Chrome 42.0.2311.90 m
    FF 37.0.1
    IE 11.0.9600.17690

What is working well for me to get it to be reproduced is to first click on the donate link in the banner, then click the PhET logo on that page (but it also just happens sometimes when first loading the page so I don't know the trigger).

**Comment by aaronsamuel137** [comment] 2015-04-17 19:29
I can't reproduce this, and I have no idea how I would address it even if I could. I assume it has something to do with how the HTML5 video player interoperates with your particular setup. It might be a Win8.1 issue. Have you experienced this on other OS versions? Does it happen often for you or rarely?

The player not advancing is possibly a bug in our code - so let me know for sure about this if you see any console messages. And exactly what happened leading up to it.

**Comment by phet-steele** [comment] 2015-04-24 18:31
Alright @aaronsamuel137 you might finally have something to go on. I encountered this in the console while running FF:

TypeError: boxes.filter(...)[0] is undefined

The video player wasn't advancing and I couldn't click the arrows in either direction. The video was NOT having the blanking out issue during this.

**Comment by phet-steele** [comment] 2015-04-24 18:32
Error: Permission denied to access property "toString"

Just black screens during this one.

**Comment by ariel-phet** [comment] 2016-09-28 22:49
Pretty sure this is no longer an issue, closing

**Closed by ariel-phet** 2016-09-28 22:49 UTC
Labels: website:front-page
