### ISSUE TITLE
Small edits to New Sims page

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#301] opened 2015-11-03 19:25 UTC
https://phet.colorado.edu/en/simulations/category/new 

We'd like to change the layout in a few ways: 
1. Left-align the video player with the page content
2. Move the link for "The Future of PhET" to the right and add the first chunk of that pages text in a paragraph below. 
3. Replace the current "switch to index"/"switch to thumbnails" text with an iconic representation. The active view is the one that is highlighted blue. If you hover over the inactive view (which is gray), it will become blue. When clicked, the new view will remain blue. 

Here is a mockup for how it should look: 
![screen shot 2015-11-03 at 12 21 53 pm](https://cloud.githubusercontent.com/assets/7852916/10918962/8437d1ca-8225-11e5-9b73-39a387aae500.png)

**Comment by aaronsamuel137** [comment] 2015-11-03 22:04
Are the icons here in font-awesome? I don't see a list icon like the one shown, though there is the icon with the boxes and an icon with three bars.

It would be easier to use font-awesome if possible, but if not that is fine too. Can you take a look and see if the font-awesome icons will work for you? If not, can you send svgs of the 2 icons in both colors?

**Comment by amanda-phet** [comment] 2015-11-03 23:01
Thank you for pointing that out... I had not thought to check fontawsome. Yes, please use the following:

Thumbnail: http://fontawesome.io/icon/th/ 
List: http://fontawesome.io/icon/list/ 

The blue was chosen because it is the current link "theme" color. Now that I think about it, let's go with black for active (#000000) and still gray for inactive (#B3B3B3 unless you have another inactive gray color in mind). 

![screen shot 2015-11-03 at 4 01 04 pm](https://cloud.githubusercontent.com/assets/7852916/10924471/1f1884d2-8244-11e5-8377-3a09b0034082.png)

**Comment by amanda-phet** [comment] 2015-11-04 21:58
I just realized that switch to index/thumbnail text is on all of the pages that list sims. We should make sure the fontawesome icons replace the text in all instances.

**Comment by amanda-phet** [comment] 2015-11-04 22:10
At the 11/4 meeting we decided to make a few more changes, so I'll send another mockup when we have all updates finalized.

**Comment by amanda-phet** [comment] 2015-12-03 00:27
OK, here is the final mockup: 

<img width="567" alt="screen shot 2015-12-02 at 5 17 55 pm" src="https://cloud.githubusercontent.com/assets/7852916/11548357/aa4fefe6-9918-11e5-9880-7c530f612c84.png">

The changes to the *current* page are: 
- [ ] Remove the New Sims page title and slide up the video player so that it is top-aligned and left-aligned with the page content
- [ ] Move the link for "The Future of PhET" to the right and add the first chunk of that pages text in a paragraph below
- [ ] Replace the current "switch to index"/"switch to thumbnails" text with an iconic representation. The active view is the one that is highlighted blue. If you hover over the inactive view (which is gray), it will become blue. When clicked, the new view will remain blue.
- [ ] Create two new h2 sections for Newest Sims and All New Sims
- [ ] Under Newest Sims, the 3 most recently added sims will go here. This will probably require a new category that we can add to a sim. The three with that category will go there, and will probably need to be manually updated as new sims are published. 
- [ ] Under All New Sims just list all HTML5 sims. These sims should also have the New Sims category applied and we can have an undergrad double-check. 
- [ ] Any sim that has been published since Area Builder will have a little ribbon/tag over the top-right corner of the screenshot that says "NEW!" (not a translatable string) 

Please let me know what you need from me- artwork, colors, etc.

**Comment by amanda-phet** [comment] 2015-12-03 00:27
@ariel-phet can you prioritize? I imagine this should come after the other things like help center, etc.

**Comment by ariel-phet** [comment] 2015-12-03 03:13
@mattpen, this is certainly lower priority, but if you need a break from the help center, this would be a nice small improvement to the website. Feel free to chip away as time allows.

**Comment by mattpen** [comment] 2015-12-17 02:12
@amanda-phet Can you send a mock-up of how the index page should look as well?  Should there be a separate "Newest Sims" section on that view also, or just leave it as is?

Can you send the colors (hex, rgb, or names) for the background and text of the "NEW" ribbon?  I can make the banner with HTML/CSS so no artwork needed. ( There might be some issues with rendering, I'll ask for artwork if the CSS doesn't look sharp. )

**Comment by amanda-phet** [comment] 2015-12-21 21:32
The index view can look the same as it currently does. There will not be a "newest sims" section. 

The "NEW" ribbon is #FDAE38.

**Comment by mattpen** [comment] 2015-12-22 05:08
Thanks @amanda-phet. I've added these changes to phet-dev.  As we don't have the "newest" category added yet, I just added the first three sims in the list to the Newest section.  Let me know once that category is added, or if there needs to be any adjustments.

**Comment by amanda-phet** [comment] 2015-12-22 18:38
So if we add a "newest" category, it will also show up in the left-hand navigation. Is it possible to make "newest" a keyword or something that is more hidden from navigation?

**Comment by mattpen** [comment] 2015-12-22 21:35
@amanda-phet That's a great suggestion.  I added a newest keyword on phet-dev and added a few sims.  The Newest panel will now only display the first three sims (alphabetically) that have the newest keyword.

Can you comment on the "new" ribbon that is overlaying the HTML5 sims?  I've noticed that if you zoom in on Chrome there are small (< 1 pixel) breaks in the orange background.  If you want this to look smoother we'll need an actual image, either with or without text is fine if translatability is not requested.

**Comment by amanda-phet** [comment] 2015-12-22 23:32
I hadn't noticed it but now that you mention it, I see it slightly in Chrome and Safari, but in FF I see a lot more pixel breaks. It looks like the shape is composed of small triangles and an overlaying rectangle. However I did need to look pretty carefully to notice this.

**Comment by amanda-phet** [comment] 2016-01-04 19:37
Based on a skype call with @mattpen we decided to make the following final tweaks to the current phet-dev page. @mattpen please check these off as they are completed. 

- [ ] Replace the main sim page title ("New Sims") and remove the sub-titles ("Newest Sims" and "All New Sims").
- [ ] Fix the grid/list icons so that the *active* one is black, and the inactive one is gray. When the user hovers over the inactive one, it should highlight black. 
- [ ] The link for "The Future of PhET" should follow the site's CSS for link colors, which is the default RGB blue and should not be specified for individual links. 
- [ ] All sims with the "New Sims" *category* will have the New! sash. Artwork was emailed to @mattpen 1/4/16. 
- [ ] A checkbox will be added to the administration pages for sims that will allow 3 sims to be listed in the special box at the top of this list. 
- [ ] This page will move to a new page titled HTML5 sims, and a proper New Sims page will be added that is based on the category. This is tracked in #346. 

Mockup of the New Sims page:

<img width="557" alt="screen shot 2016-01-04 at 12 37 03 pm" src="https://cloud.githubusercontent.com/assets/7852916/12098470/beed6dee-b2df-11e5-833f-520c999398c2.png">

**Comment by mattpen** [comment] 2016-01-08 08:19
I published the latest version to phet-dev tonight.  At the dev meeting today we decided to make the newest sims box pulled automatically by date rather than by a manual checkbox.

There is still some pixel polish that needs to be done.  Also, the new sims category has dropped to the bottom of the nav menu, I'm still trying to figure out why.

**Comment by amanda-phet** [comment] 2016-01-21 04:16
This is looking great. The only pixel-polishes seem to be 
* When the user hovers over the inactive one, it should highlight black
* There should be more space under the New Sims title so that the newest sims rectangle does not overlap the icons.

**Comment by mattpen** [comment] 2016-01-25 20:42
@amanda-phet - I deployed fixes for the above comment to phet-dev. There is now an HTML5 category page as well.  Is there anything else to be done here? Is it ok to deploy to figaro?

**Comment by amanda-phet** [comment] 2016-01-27 21:32
It looks really good to me. I like how the thumbnail/list icons are in all sim categories now as well. 

Also to clarify, the 3 newest sims are populated automatically by date? And the rest of the "new sims" are still by category, or is that also automatic now? 

@ariel-phet @arouinfar @amyh-phet @oliver-phet want to also take a look since we all worked on the design?

**Comment by amyh-phet** [comment] 2016-01-27 21:48
@amanda-phet  and @mattpen  I think this looks really good.  I like having the HTML5 category page too!

**Comment by oliver-phet** [comment] 2016-01-27 22:24
On my machine, Index/list view is showing *all* sims under the 'New SIms' category instead of only the new sims.

**Comment by mattpen** [comment] 2016-01-27 23:59
@amanda-phet - The sims are all selected automatically by date of publication of v1.  The 3 newest sims for the blue box and the 30 newest sims on the page.

@oliver-phet Good catch, I'll fix that ASAP.

**Comment by amanda-phet** [comment] 2016-01-29 18:19
Date of publication of v1? Is it possible to see these dates anywhere? I'm curious why Area Builder is not listed here when many of these were published before that point. That sim is still considered very new.

**Comment by mattpen** [comment] 2016-01-29 19:07
@amanda-phet - The actual ordering is based on the id # in the database, as the created date is missing from some of the database records.  This was discussed at a dev meeting and the consensus was that this should be identical to the publication date of v1.  It sounds like this might be a flawed assumption.  Is there a record somewhere of publication dates that I can use to double check?

**Comment by amanda-phet** [comment] 2016-02-01 23:19
> Is there a record somewhere of publication dates that I can use to double check? 

Why yes, there is! Steele just made this spreadsheet for us: https://docs.google.com/spreadsheets/d/1WfYjEWBv5bdoelxZrCnQDd5OtSd7RrbXplWPWMV-pq8/edit#gid=0

**Comment by mattpen** [comment] 2016-02-04 05:05
Excellent, thanks Amanda, I've uploaded these dates to the database.  I'll switch the sorting to these dates later this week.

**Comment by mattpen** [comment] 2016-02-05 20:46
@amanda-phet - I published the changes to phet-dev.  I confirmed that Build an Atom, Resistance in a Wire, and Ohms Law were indeed dropped from the list.  Is there anything else to be done here?

**Comment by mattpen** [comment] 2016-02-16 05:36
@ariel-phet - This is looking complete to me and I'm guessing Amanda may be out for a while. Is there any additional pixel-polish or QA to be done?  If not, I can deploy this to figaro this week.

**Comment by ariel-phet** [comment] 2016-02-16 05:59
Hmm...something is not right, on the new sims page on phet-dev, a bunch of non HTML5 sims are showing up...

Back to you @mattpen

**Comment by mattpen** [comment] 2016-02-16 06:34
@ariel-phet - The DB was out of sync, sorry about that!  It's fixed now.  

The sims that are dropped from the page are currently not the same as Amanda's list. There is some ambiguity because there were 5 sims published on 8/16/2013.  It looks like Amanda's choice was removing the oldest and alphabetically greatest?  The list that is currently dropped is below.  Is this acceptable?

Sim-name (publication date):
+ build-an-atom (8/13/2013)
+ balloons-and-static-electricity (8/16/2013)
+ ohms-law (8/16/2013)
+ resistance-in-a-wire (8/16/2013)

**Comment by ariel-phet** [comment] 2016-02-16 16:16
@mattpen that list seems good. 

One issue that seems odd, on the "new sims" page not every single sim has the "new" sash on it. for instance Least Squares Regression, Ph-Scale: Basics, and Area Builder.

That does not seem correct.

**Comment by mattpen** [comment] 2016-02-17 18:03
@ariel-phet - I updated the algorithm that adds the sash to reuse the method that adds the sims to this page, so they should be the same now.  Is this good to go?

**Comment by ariel-phet** [comment] 2016-02-17 20:02
Not quite...

If you check in another locale, it looks like the "list" and "grid" view icons are not aligned properly (see below)

![new sims](https://cloud.githubusercontent.com/assets/4051174/13122930/bfa1742e-d576-11e5-82a9-698c9140feb9.PNG)

**Comment by ariel-phet** [comment] 2016-02-17 20:05
Some different funkiness in arabic/RTL locales.

**Comment by mattpen** [comment] 2016-02-23 20:26
@ariel-phet - I deployed a fix to phet-dev.  I tested the changes on Chrome, FF, and IE in en, pt_BR, and ar_SA locales.  Does everything look ok now?

**Comment by ariel-phet** [comment] 2016-02-23 23:01
Looking good, but there are several small tweaks that should be made shown in the mockup below:

- more negative space underneath video
- sims in the "new sims" box have been more vertically centered in the box
- The video has been left aligned with the "N" in New Sims
- "New Sims" and the grid/list icons have been moved slightly tighter to the box
- more horizontal spacing between the video and the paragraph
- grid and list icon moved to right align with box (unless we always want a consistent position)

![newsims](https://cloud.githubusercontent.com/assets/4051174/13269718/7abd6d8e-da46-11e5-94f6-bc02708bc178.PNG)

**Comment by ariel-phet** [comment] 2016-02-24 00:36
HTML5 Sims page needs similar tweaks

- for all pages that are not the "new sims" page I would right align the list view icon with the right edge formed by the code base icons on the right side of the columns (shown with a red line added to the mockup below)
- similar tweaks of negative space and such are shown below

![htmlsims](https://cloud.githubusercontent.com/assets/4051174/13271714/0552f7e0-da54-11e5-9c7b-86edc6cb677b.PNG)

**Comment by ariel-phet** [comment] 2016-02-24 00:40
@mattpen let me know if you have any questions about the above tweaks, hopefully they are all pretty minor adjustments.

**Comment by ariel-phet** [comment] 2016-02-24 00:44
Oh...and it would be ideal if the "blurb" next to the video had a word or two more per line...it is very choppy reading at the moment. For instance, I think if the paragraph were such that the first line could fit "The PhET Interactive Simulations" that would be enough to make the whole blurb a bit less choppy.

**Comment by mattpen** [comment] 2016-02-24 05:41
@ariel-phet - I made the requested changes and posted this to phet-dev.  Anything else to change?

**Comment by ariel-phet** [comment] 2016-02-24 17:11
Hey @mattpen looking good! It appears that one of my requests was not clear:

For the 3 newest sims highlighted in the blue round box they should be a bit more veritcally centered in the box:
![newsimbox](https://cloud.githubusercontent.com/assets/4051174/13293911/ed79465c-dade-11e5-9e4c-2ae0cf02a7b8.png)

**Comment by mattpen** [comment] 2016-02-24 21:27
@ariel-phet - Sorry I missed that one.  I deployed a fix to phet-dev.  Can you please check?

**Comment by ariel-phet** [comment] 2016-02-25 00:13
@mattpen just one last thing (I think), and very minor

If you are on the "new sims" page and switch to "list view" the New Sims label goes away.

The "HTM5" sims page works properly, and retains the HTML5 label

Other than that all looking great!

**Comment by mattpen** [comment] 2016-02-25 05:44
@ariel-phet - The New Sims header is back on phet-dev.  Anything else to change?

**Comment by ariel-phet** [comment] 2016-02-25 05:55
Nope, I think this is good to go!

**Comment by mattpen** [comment] 2016-02-29 03:56
This was deployed to figaro tonight.

**Comment by pixelzoom** [comment] 2016-02-29 18:32
I was stumbled across the "NEW!" label for the first time when I went to http://phet.colorado.edu/en/simulations/category/html, where I was surprise to see sims that are 2.5+ years old marked as new.  Apparently the newest 30 sims are labeled as "NEW!" and added to the "New Sims" page http://phet.colorado.edu/en/simulations/category/new.  Since PhET rarely publishes more than 10 new sims per year, this algorithm guarantees that sims that are years old will be marked as new. Which seems very odd and (from the end-user perspective) make the "NEW!" label ineffective.  Reopening and assigning to @ariel-phet to make sure that this is really what you want.

**Comment by ariel-phet** [comment] 2016-02-29 18:37
@pixelzoom yes, this is what was decided, that the 30 "newest" would be our new sims. I think we can always bump that number down, but for the moment, we still wanted the bulk of our HTML5 sims highlighted on that page (since it has been only since the summer since the new sims page was our HTML5 sims).

In the past "new" sims were decided completely ad hoc, basically people would just say "hey that sim is not so new anymore" and take it off the list, and for almost 4 years Radiating charge was showing up as our newest sim! Anyhow, I don't disagree with your point, and we will revisit at some point, but for now we felt it was best to keep the bulk of our HTML5 sims labelled as new, and it will be easy to make that listing the newest 20 or such in the future.

**Comment by pixelzoom** [comment] 2016-02-29 18:37
Imo, the problem here is that you're using a quota, where N sims are always marked as "NEW!".  Newest is a temporal quality - a time (eg, first published in the past N days) would make more sense, and be more useful to the end user.

**Closed by ariel-phet** 2016-02-29 18:37 UTC
Labels: priority:3-medium, website:addressed-waiting-deploy

**Comment by ariel-phet** [comment] 2016-02-29 18:41
@pixelzoom we will take that into consideration when we do the next iteration of the website design, a that point, "new" will be a filter and this page as such might no longer exist. However, "new probably makes sense to have "new for 2015" or such...many end users only visit the site once or twice per year, so I think we will likely consider new as in new in the last academic year.
