### ISSUE TITLE
Language link splitting

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#196] opened 2015-05-15 15:59 UTC
On the wider pages, like Teaching Resources and its subsequent sub menus, the link to the Japanese language gets split between two lines:

![half jap](https://cloud.githubusercontent.com/assets/5863899/7656368/4e58633c-fae7-11e4-92d0-2d011d60fc71.PNG)

In RTL it's more clear the link actually gets split into two links:

![2 jap](https://cloud.githubusercontent.com/assets/5863899/7656440/c01ee13a-fae7-11e4-98b3-5d226495371a.PNG)

Tested on Win 8.1 browsers. In Chrome the logographs look way better:

![better jap](https://cloud.githubusercontent.com/assets/5863899/7656586/85c55ffe-fae8-11e4-90f3-ccf9d07bbe45.PNG)

than FF

![worse jap](https://cloud.githubusercontent.com/assets/5863899/7656635/f202ce7c-fae8-11e4-8903-4e5ca3f1e0c0.PNG)

**Comment by ariel-phet** [comment] 2015-05-18 16:17
This bug exists on the current site. We should fix it, but currently our teacher resources are primarily in English.

**Comment by aaronsamuel137** [comment] 2015-05-19 17:43
I can't reproduce this, perhaps is it screen resolution dependent?

Either way, I think it should be fixed now. I made the footer width match the header width regardless of the page width.

**Comment by aaronsamuel137** [comment] 2015-05-19 17:43
Assigned to @phet-steele for verification.

**Comment by ariel-phet** [comment] 2015-05-19 17:47
Fixed for me now...closing

**Closed by ariel-phet** 2015-05-19 17:47 UTC
Labels: bug
