### ISSUE TITLE
Arrows Overlap Text on "FAQ" and "Troubleshooting" pages.

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/website#129] opened 2015-04-16 17:55 UTC
Tested on 10.9.4, Chrome 41
The arrows over lap the text for each bullet point on the FAQs and Troubleshooting pages:
https://phet-dev.colorado.edu/en/faqs
https://phet-dev.colorado.edu/en/troubleshooting

![screen shot 2015-04-16 at 11 54 50 am](https://cloud.githubusercontent.com/assets/5631059/7187669/6d305748-e42f-11e4-8a0f-6d4be1a5bf01.png)
![screen shot 2015-04-16 at 11 55 03 am](https://cloud.githubusercontent.com/assets/5631059/7187671/6ef3cb32-e42f-11e4-9193-ded97001de72.png)

**Comment by orejolaphet** [comment] 2015-04-16 18:04
Also includes sub pages of "Troubleshooting".
Troubleshooting>mac https://phet-dev.colorado.edu/en/troubleshooting/mac
Troubleshooting>windows https://phet-dev.colorado.edu/en/troubleshooting/windows

![screen shot 2015-04-16 at 12 04 06 pm](https://cloud.githubusercontent.com/assets/5631059/7187835/be78b360-e430-11e4-8d43-857aae14b53a.png)
![screen shot 2015-04-16 at 12 04 11 pm](https://cloud.githubusercontent.com/assets/5631059/7187836/bf858792-e430-11e4-80e8-3dd52e90048c.png)

**Comment by phet-steele** [comment] 2015-04-17 17:37
Also seeing this on Win 8.1 today (4/17), but again don't remember seeing them on 4/13.

**Comment by aaronsamuel137** [comment] 2015-04-17 19:32
This is a new bug caused by updating the expandable text arrows to work with rtl languages. I'll work on fixing it.

**Comment by orejolaphet** [comment] 2015-04-21 17:15
This issue is no-longer present on osx 10.9.5 Chrome, FF, and Safari

**Comment by aaronsamuel137** [comment] 2015-04-21 17:18
Sounds good. I'm closing the issue in that case.

**Closed by aaronsamuel137** 2015-04-21 17:18 UTC
Labels: Other / multiple pages
