### ISSUE TITLE
Most locale links break when viewed in RTL

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#330] opened 2015-11-30 18:00 UTC
On the live site, viewing an RTL locale makes it difficult if not impossible to change back to other locales via the links at the bottom of the website (except English, nn, ko, vi, and other RTL locales are easy to click on). Noticed on Win 8.1 Chrome (personal device), and @arouinfar noticed it on her computer, too. Didn't see this on FF or IE11 as of 11/30.

**Comment by mattpen** [comment] 2015-12-24 20:33
@phet-steele - this should be fixed on phet-dev.  Its currently staged for deployment next week.  I tested it on FF, Chrome, and IE on Win 7.

**Comment by mattpen** [comment] 2016-01-25 21:26
It appears this was caused by a poorly translated string in ar_SA.  I deployed a fix to figaro and it appears to be working. Closing.

**Closed by mattpen** 2016-01-25 21:26 UTC
