### ISSUE TITLE
Double Clicking Buttons on FF

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#197] opened 2015-05-15 16:40 UTC
Double clicking "Update" on the edit profile page or double clicking "Submit Activity" while creating an activity causes an internal error for me.

Tested on Win 8.1, FF 37.0.2

**Comment by bryo5363** [comment] 2015-05-15 17:35
I did not observe this behavior on OSX 10.9.5 FF 38

**Comment by phet-steele** [comment] 2015-05-15 17:40
Try having a field blank first, where normally the site wouldn't let you proceed and give you an error message. See if anything is different.

**Comment by bryo5363** [comment] 2015-05-15 17:45
The issue is still not present

**Comment by phet-steele** [comment] 2015-05-15 17:50
I updated FF, still happens. Maybe not as consistently.

**Comment by aaronsamuel137** [comment] 2015-05-18 23:22
I can't reproduce this, though I have once or twice seen an internal error here that I haven't fully understood. I'd say for now there is nothing I can do unless I can figure out a way to reproduce it and see what is going on.

**Comment by ariel-phet** [comment] 2015-05-19 01:04
@phet-steele - please hammer on this for awhile and see if you can figure out a consistent way to reproduce. Perhaps have the browser console opened and when you get the error see if the console is reporting anything that you can give to @aaronsamuel137 for more information?

**Comment by aaronsamuel137** [comment] 2015-05-19 01:23
The browser console won't help here, since it is a server side issue and not something that happens in the browser.

**Comment by aaronsamuel137** [comment] 2015-05-19 19:25
This is partially fixed. Now you will no longer get an internal server error when clicking fast like this. However, in cases where the server error would have happened, the navigation links will disappear.

I am really stumped as to why this is happening. At least it's a little better than it was.

@phet-steele, can you verify the server error is no longer happening for you?

**Comment by phet-steele** [comment] 2015-05-20 04:02
Yup, no more error but missing the navigation links.

**Comment by aaronsamuel137** [comment] 2015-05-20 14:40
By the way - this issue also seems to be present on the main website, and it doesn't seem browser specific. I have reproduced it in Chrome.

I also don't think it is too big a deal, since a typical user would not be clicking many times so quickly.

**Comment by zepumph** [comment] 2015-07-12 14:49
Can this issue be closed @aaronsamuel137?

**Comment by aaronsamuel137** [comment] 2015-07-13 14:18
The issue is only partially fixed so I think we should leave this open as a reminder? Although it is very low priority since it is such a minor issue.

>This is partially fixed. Now you will no longer get an internal server error when clicking fast like this. However, in cases where the server error would have happened, the navigation links will disappear.

If you can reproduce and fix it, that would be great @zepumph, but don't spend too much time if you get stuck. I had a really hard time when I was trying to track this down.

**Comment by zepumph** [comment] 2015-07-20 22:02
I can't seem to reproduce this, as much as I try. I'm on Windows 8.1 and Chrome Version 43.0.2357.134  and FF 39.0. If you could be a little more specific about what your doing, and perhaps try to see if you can still recreate it @phet-steele, that would be great thanks.

**Comment by aaronsamuel137** [comment] 2015-07-22 15:52
@phet-steele is gone for the summer (I think). I had a hard time reproducing this at first, but eventually did it by literally clicking as fast as I possibly could.

**Comment by zepumph** [comment] 2015-07-22 16:58
Oh yeah I think he is thanks. I attacked this on the front end, because I thought it would be easier, and (assuming it's actually fixed from my testing) it was very easy. You can take a look at it on phet-dev @aaronsamuel137.

**Comment by aaronsamuel137** [comment] 2015-07-22 18:48
Looks good @zepumph. It doesn't actually address whatever strange error is happening on the server side, but at least it prevents double clicking too fast.

One minor bug, looks like you accidentally added a "\" to the beginning of ContributionEditPanel.html. After you remove this, feel free to close.

**Comment by aaronsamuel137** [comment] 2015-07-22 20:43
OK looks good now. Closing.

**Closed by aaronsamuel137** 2015-07-22 20:43 UTC
Labels: bug
