### ISSUE TITLE
Activity Types

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/website#159] opened 2015-05-08 20:02 UTC
@ycarpenterphet and I were discussing the changes to the website, including the activity submission page. The activity types (Lab, Homework, CQs, Demonstration, Other) could be improved if we make a few tweaks. Right now, we are missing a critical type that describes an inquiry-based activity that is not a Lab, Homework or really any of the types! While we are at it, perhaps these could all be improved. We are proposing two things: 

1. Add "In-Class Activity" as a type. This will cover 99% of the types of activities *I* write, and many many activities others submit. 
2. Revisit the "Concept Questions" type. Many people aren't sure if this means Conceptual Question, or think its abbreviation of CQs means Clicker Questions... Has anyone thought about this and have an idea worth tossing around? 

@patricialoeblein can you weigh in on this?

**Comment by ycarpenterphet** [comment] 2015-05-08 20:08
With regards to the "In-Class Activity" type, I thought I'd share this reflection.

When we uploaded many of the activities produced by the college faculty partners as part of the faculty working group in chemistry last fall, we had to mark guided-inquiry activities as "Other". While we know that faculty could potentially use them as homework instead, we wanted a category that reflected that we had designed them for in-class use, and included facilitation tips and guidance for instructors.

We added the words "Guided-inquiry activity" to the activity title, but wished we could categorize it as something more fitting than 'Other'.

**Comment by patricialoeblein** [comment] 2015-05-08 23:36
I am glad we are reflecting on the types because I agree that the categories are unclear. I know we had a discussion about the categories in a meeting recently, but I don't remember any  consensus,

 Personally, I seldom use the homework category anymore because many of my labs can be done for homework. I do have a few that I wrote specifically for homework and then compared the results of having used in class. There was a time where I found HS students could not do the more open designed activities without in-class guidance, but the culture of using technology has changed enough that I no longer find a difference. My students often chose to do the PhET labs outside of class because they feel they can do them well if they need to prioritize class time for something else.  

So, I think it would be interesting to consider what the learner is doing as opposed to where they are doing it.  I like the way Yuen-ying described how they chose "Other", so  I have described my approach to selecting the categories we presently have with a few notes about how I have seen others use them.

Lab:  I usually select Lab to imply individuals or partners doing experiments with a wrapper. The wrapper include concept questions that follow the guide for designing activities http://phet.colorado.edu/files/guides/Activities/PhetGuideActivityDoc_v8-final.pdf. Personally all my activities include teacher lesson plans so they have ideas for facilitation and guidance. In K12,  just having a worksheet is not normal for sharing a quality teaching idea (although many teachers on PhET just have a worksheet, so if I give them a Gold star, I encourage them to improve their lesson by adding lesson plans) 
CQ: I reserve this for clicker questions although I have some questions that are not multiple choice to initiate more discussion.  Some authors have selected this when they really wanted to say they used this for a teacher led discussion however. 
Demonstration: I use this for  a teacher  led large group discussion which include concept questions which drive the  experiments demonstrated.
Homework:: For my activities, I only select HW if I have specifically written a version that I adapted during the time I thought that in class versus out of class might need different directions or learning goals.I have used HW  when I uploaded activities that Kathy and Carl used specifically as "homework" (see http://phet-downloads.colorado.edu/files/activities/3048/HW09_SIM.pdf) . I see these a check points of learning that can be used as formative assessment outside of class. 
Other: I would imagine this could be used for curriculum alignment docs like Julia's http://phet.colorado.edu/en/contributions/view/3871. We do hope to add more for other subjects, but we have discussed putting them somewhere else. I like them in the activities because it will be easy for teachers to share them here. I don't know if we would like to add a category to make this more clear. I see that under "Other" there are mostly UG activities, so perhaps we should look at those to see what authors thin" Other" means.. 

I can imagine that in college the term "Lab" might seem restrictive to a period of time designated a Lab, and that we want to help faculty think of using PhET more flexibly like in recitation .  I believe this is the type of activity to which Yuen-ying selected "Other" , but I am not certain.   I wonder if "Tutorial" might be  more well known in some teaching communities? 

I have time to skype about this on Monday, but then I am off to Chicago for the rest of the week. Following week, I have standardized testing and after that FINALS:).

**Comment by amanda-phet** [comment] 2015-05-12 18:45
Based on what you wrote, @patricialoeblein , it sounds like you don't write many guided-inquiry activities that are in need of a new type. 

The label In-Class Activity is not so much about the location- it is a guided-inquiry activity that is done in class (so, not for homework). However, "guided-inquiry activity" is pretty general and might overlap too much with Lab, Homework, or Demonstration, so we need a separate distinct category. If you have any suggestions about the name for this new type please send them along! 

If you think there needs to be clarification on the website about what the activity types are intended to represent, perhaps we can find room somewhere to describe these to users.

**Comment by patricialoeblein** [comment] 2015-05-12 20:35
I have been thinking about this and have a proposal. How about:
Lab, Formative assessment (which covers clicker questions and homework like the ones KP and Carl wrote), Tutorial (for UG class guided inquiry), Demonstration 

I lean away from "Guided Inquiry" as a label because the language of NGSS moves strongly  away from using "inquiry" . I have some concern that explicitly using Guided Inquiry makes us seem out of touch. In the UG physics community, we use" Tutorial"  frequently. I wonder what YY thinks might be a good option to "Other" ?

**Comment by amanda-phet** [comment] 2015-05-12 20:38
I like the Formative Assessment type! 

However, this still doesn't address the need for a new category for K-12 guided-inquiry activities.

**Comment by ycarpenterphet** [comment] 2015-05-12 20:47
I'm not a fan of the word 'Tutorial' for this purpose, even though it is popular in UG physics.

The word Tutorial in the UG community specifically brings to mind activities that are (a) facilitated by TAs (not the instructor), and often (b) are meant to support students AFTER content delivery, typically in addition to and after the material is covered in lecture. This conveys a sense of 'extra-practice' rather than how students are initially learning the content.

Some of the guided-inquiry activities we posted last fall for UG chemistry were intended to be facilitated by the primary instructor and to be the students first exposure to these topics, much more akin to the K-12 guided inquiry activities that Amanda is describing. Some were intended for use in recitation.

I think in both cases, the key features are that students are hands-on with the sim, learning new material, and that there is a facilitator (distinguishing this from out-of-class work).

**Comment by patricialoeblein** [comment] 2015-05-12 20:50
"Tutorial " in the physics community is a guided inquiry activity usually done in groups in class with some facilitation by someone like a TA, LA, or prof. I don't have a strong opinion about that word choice. However,  I am not sure how I would chose ""lab or "guided inquiry" if I were adding a new activity. All my labs by definition of the Gold star guidelines are guided or full inquiry. Are there other ideas since I am conflicted about the use of Guided inquiry?

PS I am in chicago and will soon be unavailable when the conference starts.

**Comment by patricialoeblein** [comment] 2015-05-12 20:57
I was typing at the same time as YY. I can see tutorial doesn't fit the need she has when she uses "Other". Is there a proposal for something other than guided inquiry since it covers more of a strategy than a descriptor of activity. Many people would say their demos and clicker questions use guided inquiry in K12 community. In the old science standards, using Inquiry was the first standard and was meant to be a process used widely in all activities.

**Comment by amanda-phet** [comment] 2015-05-12 21:26
The original proposal was "In-Class Activity," so we could avoid "Guided-Inquiry Activity."

Another option I came up with was "Guided Activity."

**Comment by patricialoeblein** [comment] 2015-05-12 21:54
I like guided activity if YY thinks it would fit the needs of the UG.

**Comment by amanda-phet** [comment] 2015-05-26 16:36
@aaronsamuel137 Can you please add "Guided Activity" as an activity type to the database? While we're updating other activity information, this would be very helpful to have.

**Comment by aaronsamuel137** [comment] 2015-05-26 16:54
I haven't read through all the comments on this issue. Just to confirm: the one thing I need to do is add a "Guided Activity" type?

**Comment by patricialoeblein** [comment] 2015-05-26 16:58
Amanda, would this be a good time to consider also changing Concept questions to Formative Assessment?

**Comment by amanda-phet** [comment] 2015-05-26 17:14
Yes @aaronsamuel137 that is correct. Just add the "Guided Activity" type.

**Comment by amanda-phet** [comment] 2015-05-26 17:14
@ycarpenterphet can you comment on the Formative Assessment type since you did not comment earlier? You and Trish both write a lot of Concept Questions.

**Comment by aaronsamuel137** [comment] 2015-05-28 01:11
Guided Activity added. Assigning to @amanda-phet for review. This should be live on the main site (and phet-dev)

**Comment by amanda-phet** [comment] 2015-05-28 02:11
I see Guided Activity as an option, but when I check it and uncheck Lab, Lab still remains on the activity. Also, there is a strange bug:
![screen shot 2015-05-27 at 8 09 53 pm](https://cloud.githubusercontent.com/assets/7852916/7851407/83526bb8-04ac-11e5-9a9a-1ab657d3d6c7.png)

**Comment by aaronsamuel137** [comment] 2015-05-28 05:51
Looks like each activity has an abbreviated name that shows up in the table. I have added the string "Guided" as the abbreviation for "Guided Activity" - but I can change it if you'd like. Just let me know.

I'll look into the issue where the Lab is still showing up tomorrow.

**Comment by aaronsamuel137** [comment] 2015-05-28 18:02
This is a bug. Currently you can't remove any subjects, levels, types in contribution edit. This is leftover from the old implementation before the redesign and never got tested until now.

**Comment by aaronsamuel137** [comment] 2015-05-29 20:36
I'm tracking the bug where you can't remove types, etc. in #211. As far is this issue goes, assigning back to @amanda-phet for review or next steps.

**Comment by ycarpenterphet** [comment] 2015-05-29 21:32
@amanda-phet @patricialoeblein I took a look at both of your comments on replacing 'Concept Questions' (CQs), with 'Formative Assessment' and I took a look at activities submitted by non-PhETteam members in the existing CQ category.

From community members, there are only one or two activities under CQ that are multiple-choice questions that might be used with personal response systems or class voting. All of the rest (which is a decent number of user-submitted activities) are activities that I would categorize as these guided activities (with big conceptual questions as part of an activity worksheet).

When I think of the purpose of these categories for a teacher sorting the activities on the website (or browsing for an activity to use), I think of being able to use them to quickly find activities that I can use in a given context. For example, if I have a small (<50 student) college class, I might be looking for a guided activity or HW for use in/out of class. If I have a large lecture, I am more likely looking for a Demo, lab, or for multiple choice questions I can use to prompt peer discussion in class.

I really want the multiple choice questions to be easy to find (or sort by) for college instructors, especially since this style of question has found substantial traction in introductory college teaching as an accessible entry point into active learning for college faculty.

I can't speak for K-12 teachers, but I suspect the context in which a teacher would be looking for multiple choice questions is different from one where they are looking for an activity with long-answer questions (they might want both, but when looking for materials, being able to easily distinguish between the two I think is advantageous).

As such, I would almost prefer to have a category entitled 'Multiple-choice concept questions' (or MC for short). I know that CQ is a popular shorthand for 'clicker question' or 'concept question' (multiple choice implied) among college instructors, but based on the pool of submitted activities, it is clearly not prompting this distinction for our users.

Thoughts?

**Comment by amanda-phet** [comment] 2015-05-29 22:26
Thank you for taking the time to look through activities and providing us with this insight. I am not surprised teachers selected CQ incorrectly since we didn't have the Guided Activity option until now. 

When I personally see CQ I immediately think Clicker Question, then have to remember that it means Concept Question on our site, so it seems like a good idea to make a change. I do not have a preference, although "multiple-choice concept question" seems really clear what it is. It's just a really long title. I also worry that we'd make the change and other activities will incorrectly be labeled as MC, adding to more confusion. Perhaps we can reach out to those authors individually and ask them to review the category now that we have new categories.

**Comment by patricialoeblein** [comment] 2015-05-31 22:31
I still like "Formative Assessment"  partly because mine questions are not all multiple choice. how does that sound?

**Comment by ycarpenterphet** [comment] 2015-05-31 23:27
@amanda-phet I agree that if we were to just convert the category, it would not work well, since the category currently contains two very different types of activities: [1] heavily [although not entirely] MC questions, typically on powerpoint slides, and [2] student hands-on activity worksheets. We would likely have to reach out to users to retag their activities (and perhaps grandfather out the CQ label gradually). I also agree that for some folks the tag CQ immediately brings to mind "clicker question" - but we should keep in mind that at the time that folks are tagging their activity, they are presented with these categories in full-length, not abbreviations, so they see "Concept Questions" - which for many was the best fit for their student worksheets.

@patricialoeblein As an instructor searching the activity database, I would rather have someone, like you, who has both multiple-choice and discussion prompt style questions label an activity with both of these tags - since knowing what types of questions are in the item are incredible helpful and time-saving when I am looking for activities to use in my class.

The type of questions is, in a sense, a more useful predictor of whether I should download and open an activity that where it was intended to be used (in-class, out-of-class, in lab, as formative assessment, as summative assessment).

This is especially true for college faculty who, in large classes, can't leverage student-hands-on activities as much -- and creating good multiple choice options that tackle concepts is hard and time-consuming. :)

**Comment by amanda-phet** [comment] 2015-06-01 16:26
@ycarpenterphet I'm not sure I understand your final opinion on this matter- if you like Formative Assessment or not. Can you clarify what you mean here? What tags would you use in this case? 
>As an instructor searching the activity database, I would rather have someone, like you, who has both multiple-choice and discussion prompt style questions label an activity with both of these tags

**Comment by ycarpenterphet** [comment] 2015-06-01 18:26
Ah, sorry. To clarify, I don't like Formative Assessment, because it doesn't tell me what types of questions I'm likely to find in the activity (forcing me to open each activity individually).

I would prefer Multiple-choice concept question (MC), and, if this does not cover other types of questions, then some other tag like (brainstorming these, so they might not work right) "Discussion prompts" or "Short answer questions" or "open response questions".

Then one of Trish's powerpoints that includes both MC and discussion prompts could be tagged with both, while one of the many activities currently under CQ that is a student-worksheet would likely get a tag like "Guided Activity" or "Short answer" or something, but wouldn't share the MC tag.

That way I know if I am in a 300-student lecture and really need some MC questions to use with clickers, I can find those easily.

Does that clarify?

**Comment by amanda-phet** [comment] 2015-06-01 19:22
Yes! So you're saying you'd prefer two new categories to replace Concept Questions. We can wait to see what @patricialoeblein thinks. In the mean-time, let's re-tag activities that are guided with the new type "guided activity", and wait on this particular type?

**Comment by patricialoeblein** [comment] 2015-06-01 20:04
I like the idea of the categories suggested and that I would multiple tag MC and discussion prompts.  Are the categories - MC, Guided , discussion prompts going to replace to replace CQ and HW ? could someone please give me the full list just so I can check. I am working  outside a library for a few minutes to have wifi.

**Comment by amanda-phet** [comment] 2015-06-01 20:14
Multiple-choice concept question (MC) and Open-response concept question/Discussion prompt/? (Open/Prompt/?) would be added as types, while Concept Questions (CQ) would be deleted as a type. 
*If we do it this way, we can make the change immediately and no one's activities will be incorrectly re-classified. They will simply not have the CQ type associated with them, and when the author goes in to edit their activity they can select the appropriate activity type.*

I don't think Homework (HW) needs to be deleted, because a homework task wouldn't fit in any other activity type. 

Guided activity (Guided) has already been added as an activity type! Feel free to go in and edit any of your activities if you think they belong under this type!

**Comment by patricialoeblein** [comment] 2015-06-01 20:29
The discussion has been a little piece wise, so I think we need to decide if this is the final list or if there are still discussion issues.  I think I understand the types will be :Lab, HW, MC, Discussion Prompts, Demo,Guided, Other ? [ I think open response is not the same as a discussion prompt; my slides and some other MS ones are definitely for group discussion. Open response implies assessment like on standardized test in my world]
These work for me if this is the place to vote

**Comment by ycarpenterphet** [comment] 2015-06-24 02:24
Sorry for not commenting sooner, team.

I like this new scheme, with Lab, HW, Demo, MC concept Q, Discussion prompt, Guided Activity, and Other, as well as @amanda-phet's suggestion that we delete the old CQ category which contains a mixture of things. We likely will want to notify the activity writers and encourage them to re-classify their activity.

What will be the shortform (shown in the table) for the discussion prompt? Perhaps "Discuss"?

Also, I've started switching the chemistry faculty working group's activities to the Guided Activity type, as appropriate

**Comment by amanda-phet** [comment] 2015-06-24 17:25
I think "Discuss" is the only short form that would work for Discussion Prompts, so let's go with that! 

@aaronsamuel137 Will you please *add* two activity types: 
Multiple-Choice Concept Questions (MC) 
Discussion Prompts (Discuss)

and *delete* the current type:
Concept Questions (CQ) 

Then we can close this issue.

**Comment by patricialoeblein** [comment] 2015-06-25 14:52
I like the new categories:)

**Comment by aaronsamuel137** [comment] 2015-06-30 15:27
I can make this change. What should I do about activities that are already marked as CQ in the database? Are there any of these left?

Also, the Multiple Choice name is a bit long. It looks a little out of place:

![screen shot 2015-06-30 at 9 25 00 am](https://cloud.githubusercontent.com/assets/3193912/8434698/242bf7ee-1f0a-11e5-802f-64abb2a64693.png)

Maybe not a big deal, just wanted to point it out.

**Comment by aaronsamuel137** [comment] 2015-06-30 19:01
Assigning to @amanda-phet to answer these last questions.

**Comment by amanda-phet** [comment] 2015-06-30 19:04
That is confusing. Can the text wrap around under the words only, and not under the box? 
![screen shot 2015-06-30 at 1 03 27 pm](https://cloud.githubusercontent.com/assets/7852916/8439315/7326c91e-1f28-11e5-95d3-2d7bd243e451.png)

We decided that the few activities that have the "concept question" type will need to be manually updated with an appropriate type- either by the original author or a PhET team member.

**Comment by patricialoeblein** [comment] 2015-07-01 02:39
I thought the Concept Question category would be replaced by Multiple Choice and Discussion Prompts. I believe this decision is documented in this ticket. For my activities, it would be ok to make them all MC and then I could add Discussion prompts. If we do this for all CQ activities, I could review them and make changes. I start work sometime soon. Oliver is working on the paperwork.

**Comment by aaronsamuel137** [comment] 2015-07-01 14:39
@amanda-phet, I have deployed this to phet-dev. Let me know if it looks good to you.

**Comment by amanda-phet** [comment] 2015-07-01 15:58
@aaronsamuel137 Is it possible to have the text wrap around so that it is not under the checkbox? I worry that it will look like we are describing the following checkboxes as concept questions.

**Comment by aaronsamuel137** [comment] 2015-07-01 16:12
I think it is doing that, if I understand what you mean. Here is what it looks like on my screen:

![screen shot 2015-07-01 at 10 10 22 am](https://cloud.githubusercontent.com/assets/3193912/8459305/75979528-1fd9-11e5-9409-876809f83ebc.png)

If that looks right to you, try a hard refresh (on phet-dev) and see if it turns up. Otherwise, let me know what else needs to change.

**Comment by amanda-phet** [comment] 2015-07-01 17:15
Sorry, when I saw the updated types I assumed I didn't need a hard refresh. That fixed it! Looks great. 

There are some activities that *only* have the current CQ type (ex: http://phet-dev.colorado.edu/en/contributions/view/3032). Will the activities still display CQs until edited? That is what I am seeing on phet-dev. Works for me. 

From Steele's testing on the new sim pages, I know an issue was addressed regarding activities with no types, so let me know if you see anything odd.

**Comment by aaronsamuel137** [comment] 2015-07-01 17:41
Yep activities will still display CQs, just like on phet-dev. You just won't be able to create new CQs or search by CQ.

**Comment by amanda-phet** [comment] 2015-07-01 18:41
That looks like a good option to me. Thanks for making this change!

**Comment by aaronsamuel137** [comment] 2015-07-01 23:35
Deployed to figaro. Feel free to close the issue @amanda-phet if it looks good to you.

**Closed** 2015-07-02 17:48 UTC
Labels: High Priority
