### ISSUE TITLE
Able to get URL and page out of sync? 

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/website#536] opened 2016-11-28 14:35 UTC
I was able to get in an odd state on the website, that I wanted to report. When I visited the teacher resources page after being at the area builder sim, the URLs got out of sync. See image. 
![image](https://cloud.githubusercontent.com/assets/5096804/20672090/44b4dba0-b53d-11e6-90fa-ad11ff436774.png)

**Comment by kathy-phet** [comment] 2016-11-28 14:48
Can't seem to reproduce this issue --- I'll let you know if it comes up again.

**Comment by mattpen** [comment] 2016-11-28 17:27
@kathy-phet - I can't reproduce it either.  It seems likely to be a browser bug instead of a bug in our website application, i.e. just as likely to occur on any other website as it is on ours.

The only way I could get close is by typing a new address in the navigation bar, hitting tab to auto complete, then clicking on the page somewhere (in Chrome).  It looks like the URL has changed, but its just saved what you typed.

![image](https://cloud.githubusercontent.com/assets/11747676/20678715/fb05c09c-b554-11e6-8af0-431f510d76e9.png)

**Comment by ariel-phet** [comment] 2016-11-28 17:28
This does not seem worthy of any more investigation, and has never been reported by a user or by our team. Closing

**Closed by ariel-phet** 2016-11-28 17:28 UTC
Labels: type:bug
