### ISSUE TITLE
404 error on legacy sim page before HTML5 version made visible

### ISSUE THREAD

**Issue by arouinfar** [phetsims/website#538] opened 2016-11-28 18:35 UTC
@jessegreenberg has pushed the HTML5 version of Gravity and Orbits to the site, but the sim has not yet been made visible. 

I wanted to check the Java version to find the original description, but I'm running into a 404 error. The sim thumbnail points to:
https://phet.colorado.edu/en/simulation/legacy/gravity-and-orbits

I can still access the legacy sim page metadata using the admin tools, so it's not a critical issue from my end. However, there could be teachers who are trying to use the legacy sim in their classroom and are unable to do so.

Other legacy pages appear to be working, so this issue may clear up once I make the HTML5 version visible. @ariel-phet in effort to get the HTML5 version out as soon as possible, I am going to copy and paste the Java metadata verbatim, make the sim visible, and then tweak as necessary.

**Comment by arouinfar** [comment] 2016-11-28 18:41
Tagging @oliver-phet because phethelp may receive some emails related to this issue.

**Comment by ariel-phet** [comment] 2016-11-28 18:49
Duplicate of #539, closing

**Closed** 2016-11-28 18:49 UTC
Labels: type:bug, type:duplicate
