### ISSUE TITLE
Enable looking up a user by email without case-sensitivity

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/website#155] opened 2015-05-07 20:53 UTC
From #119:

> One slightly related question I have - in the past I've noticed an issue where if the email address is not entered with correct capitalization, it will not find the user. (I tried entering "H.alhadlaq@gmail.com" instead of "h.alhadlaq@gmail.com" and the website gives an error. Is it possible to not require proper capitalization for user emails?

**Comment by aaronsamuel137** [comment] 2015-06-17 22:38
Assigning to @zepumph. Not high priority. You might have to look into searching case-insensitively in postgres. We'll want to find a way to do this, but that doesn't slow look ups down too much.

**Comment by zepumph** [comment] 2015-07-07 20:27
Assigning to @aaronsamuel137 for review

**Comment by aaronsamuel137** [comment] 2015-07-07 20:55
Commit looks pretty good. We might want to consider creating an index on lowercase email since currently we have one one email. Does this sound like a good idea to you @jonathanolson?

Something like: 
```sql
CREATE INDEX phet_user_lower_emailindex ON phet_user ((lower(email)));
```

Are you up for trying this on phet-dev and testing? Assigning to @zepumph

**Comment by jonathanolson** [comment] 2015-07-08 05:12
Seems presumably safe enough, and an index would help the lookups. The part before '@' is technically case-sensitive, but de-facto case-insensitive (see http://programmers.stackexchange.com/questions/128297/programming-around-email-address-case-sensitivity or other notes).

**Comment by aaronsamuel137** [comment] 2015-07-13 14:20
We decided we want to make the main login non-case-sensitive too.

**Comment by zepumph** [comment] 2015-07-14 18:12
Added changes to master so that you can now login with a non-case-sensitive email. I'll now work on creating an index for lower-case email lookups. @aaronsamuel137 can we skype soon about doing that, thanks.

**Comment by aaronsamuel137** [comment] 2015-07-14 21:54
Discussed over Skype. Code changes look good to me. We'll want to do a little testing on phet-dev to make sure logging in is working correctly, then deploy and add the index to figaro.

**Comment by zepumph** [comment] 2015-07-15 20:41
After testing case insensitive emails for user login, I realized there was a really weird error based on incredibly unexpected behavior, dependent on which elements of the email were capitalized.  After researching further it turns out that the salted password was at fault, and as a result. The login email in non case sensitive for the entire string save the first 6 characters.

Going forward, we can either keep it the way that it is, meaning that we call it good saying the feature works for all but the first 6 characters, and hope that people remember those characters of their email address. 

Otherwise I think that only solution is to change everyone's password based on a lowercase salt. It should be pretty easy, and only needs to be run once.

I will discuss this more with @aaronsamuel137.

**Comment by zepumph** [comment] 2015-07-15 21:52
Moving forward: two topics of discussion::
New users are entered based on lower case email.
    Do it high enough up such that we don't need LOWER() in any hibernate queries or to salt the pw
Go back and change the 3000 ish users with capitalizations in their email.
    write a script much like newSimPagesMerger.java. To be run once in phetWicketApp.java then removed.

**Comment by zepumph** [comment] 2015-07-15 21:56
When going back, we will update emails to lower case, and change salted pwds.

NOTE: we no longer will need a lower case index, as it will be the same as the normal email index

**Comment by aaronsamuel137** [comment] 2015-07-15 21:58
Also, you'll want to make a test email with some capitalizations before running the code to update the old emails, just to make sure it works as expected.

**Comment by zepumph** [comment] 2015-07-20 18:41
I started to work on a script to manually change all the database entries to lower case emails. This part is easy, but then to recalculate the salted passwords, we need the password, not the previously salted and hashed password, which is the only thing stored in the database. I believe to fully implement this the way talked about above, we will need to create a dialog, where these users with upper case emails are flagged, and on next login, they are forced to changed their password and the salt is recalculated then. I will wait for @aaronsamuel137  to get back from vacation to discuss it more with him.

**Comment by aaronsamuel137** [comment] 2015-07-22 20:35
Because of the nature of password salting, we have decided not to update old users in the database who used capital letters in email addresses. For these users (~3000 out of ~70000), they will need to use their original capitalization to log in. For new users and existing users who didn't use capital letters, email addresses will no longer be case sensitive.

Feel free to close this issue when you have finished work on it @zepumph.

**Closed** 2015-07-22 20:36 UTC
