### ISSUE TITLE
Add new reporting to Admin/Statistics page

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/website#351] opened 2016-01-02 18:15 UTC
Rework "General Statistics" (found under Admin/Statistics) from OLD: 
Total visible simulations: 160
Total activities: 1238
PhET activities: 227
Number of languages (including English) that sims are translated into: 82
Number of sim translations (including English): 5665

Number of users: 118918
Users subscribed to receive our newsletter: 86495
Users subscribed to receive simulation notifications: 712
Users with newsletter-only accounts: 3464

To NEW list: 
Total visible Java simulations: 
Total visible HTML simulations: 
Total activities: 1238
PhET activities: 227

Java Sims: Number of languages (including English) that sims are translated into: 82
Java Sims: Number of sim translations (including English): 5665

HTML Sims: Number of languages (including English) that sims are translated into: 
HTML Sims: Number of sim translations (including English):

Website: Number of languages that website is translated into: 

Number of user accounts: 118918
Number of user accounts with good/confirmed emails: 
Number of users with NEW updated profiles: 
Number of users that still have OLD profiles: 
Number of new user registrations in previous 30 days: 
Number of TEACHER or TEACHER EDUCATOR users:  

Users subscribed to receive our newsletter: 86495
Users subscribed to receive simulation notifications: 712
Users with newsletter-only accounts: 3464

**Comment by mattpen** [comment] 2016-01-04 16:01
@kathy-phet - do we need statistics on Flash sims here too, or just Java and HTML?

**Comment by mattpen** [comment] 2016-01-04 16:58
Website: Number of languages that website is translated into:

I'm assuming this should be the number of visible translations as opposed to all translated languages or supported locales.  If I'm wrong please correct.

**Comment by mattpen** [comment] 2016-01-05 22:16
@kathy-phet - I'll publish these revisions to phet-dev tonight.  The only thing missing will be "Number of user accounts with good/confirmed emails:" which is dependent on #349

**Comment by mattpen** [comment] 2016-01-06 06:26
@kathy-phet The new statistics page is up on the main site now.  I'm still working on flagging users whose emails have bounced, but that statistic should be fixed soon.

**Comment by kathy-phet** [comment] 2016-01-06 07:46
Hi Matt, This is looking great. I realized that it would be good to also have the intersection of the translations - since I cannot just add these to get the total number of languages that sims are translated into. 

So can you modify to be: 

Total Sim Translation Languages (including English): (this will be less than 79+17, but should be larger than 79 because I had 80 in my DRK12 report)
Total Number of sim translations (including English): (this should be just the two below added)

Java Sims: Number of languages (including English) that sims are translated into: 79
Java Sims: Number of sim translations (including English): 4338

HTML Sims: Number of languages (including English) that sims are translated into: 17
HTML Sims: Number of sim translations (including English): 179

Thx! 
Kathy

**Comment by kathy-phet** [comment] 2016-01-06 17:13
Sorry Matt - the "Java Sims" line should really be Jave/Flash Sims" 

Java/Flash Sims: Number of languages (including English) that sims are translated into: 82
Java/Flash Sims: Number of sim translations (including English): 5665

**Comment by mattpen** [comment] 2016-01-08 08:23
This was published to phet-dev tonight.  The statistics are off because the database has not been synced with figaro recently.

**Comment by kathy-phet** [comment] 2016-01-08 08:30
Looks good to me! Thanks.

**Comment by mattpen** [comment] 2016-01-13 06:25
@kathy-phet - These changes to the statistics page are now live on figaro, including the results from the script to flag users whose emails have bounced.  

Are there any other changes to be made here? Is this ok to close?

**Closed** 2016-01-23 16:00 UTC
