### ISSUE TITLE
Improving website stability after sim pages depoloy (Tomcat)

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/website#220] opened 2015-06-03 16:28 UTC
Apparently tomcat has been having some stability issues since the latest website deploy.

@kathy-phet has requested some investigation as the top priority. @aaronsamuel137 please do what you can here and ideally if @jonathanolson can make some suggestions until he gets back in town.

**Comment by aaronsamuel137** [comment] 2015-06-03 16:34
New Relic warnings from last night:

> Today, 5:13	Incident closed
Today, 5:08	Close: 'Memory > 90%' on 'figaro.colorado.edu'
Today, 4:58	Open warning: 'Memory > 70%' on 'figaro.colorado.edu'
Today, 4:55	Open warning: 'Fullest disk > 70%' on 'figaro-dev.colorado.edu'
Today, 4:55	Open warning: 'Fullest disk > 70%' on 'figaro.colorado.edu'
Today, 4:55	Open critical: 'Memory > 90%' on 'figaro.colorado.edu'
Today, 4:55	Incident opened

Interesting that figaro-dev and figaro both showed warnings at the exact same time. Makes me wonder if OIT was running a background process of some kind then that was taking resources away from tomcat.

**Comment by aaronsamuel137** [comment] 2015-06-03 16:42
The memory trends from last night are not too unusual:

![screen shot 2015-06-03 at 10 39 47 am](https://cloud.githubusercontent.com/assets/3193912/7965779/f5b959f2-09dc-11e5-9670-9d0591ceb311.png)

But it looks like something happened that delayed the garbage collection process, and hence gave rise to the memory issues:

![screen shot 2015-06-03 at 10 39 56 am](https://cloud.githubusercontent.com/assets/3193912/7965811/249b1544-09dd-11e5-856e-9074af54ce66.png)

**Comment by aaronsamuel137** [comment] 2015-06-03 16:56
Tomcat was sick last night 3 times for a period of about 2 minutes each over a 15 minute window, at the same time as these memory issues were occurring.

Sick times:
>4:46 - 4:52 AM
4:55 - 4:56 AM
4:58 - 5:00 AM

It seemed to re-stabilize by itself after the garbage collection happened.

**Comment by ariel-phet** [comment] 2015-06-03 17:08
@aaronsamuel137 - I wonder if there are some interactions with Varnish occurring? I recall vaguely that Varnishes caching strategy depends on which pages get hit lots, and that there is some advantage to "preloading" which pages should be cached. In many ways pretty much every page on the website changed, and if I recall Varnish gets more stable as these pages get hit more.

**Comment by aaronsamuel137** [comment] 2015-06-03 17:13
I think Varnish is helping out a lot here. Most of the website should be cached by Varnish, so most pages will still work even when tomcat is sick. It's just that pages that require logging in will not work so well when tomcat is sick - though they may still work very slowly.

Anyway, I don't think interactions with Varnish are causing these issues - but Varnish is definitely helping out a lot here by taking a lot of the load off of tomcat.

**Comment by aaronsamuel137** [comment] 2015-06-03 17:16
Based on the garbage collection CPU chart above, it looks like tomcat is still up and running, but any requests that come in are competing for CPU resources that are mostly being used up doing the garbage collection.

**Comment by aaronsamuel137** [comment] 2015-06-03 22:18
Tomcat went sick again for about 1 minute this afternoon at 2:05. I don't see any memory issues this time, and no indication of a traffic spike. Total mystery as to what happened here. Might not be related to the previous issues.

In any case, unlikely this short sick time had much of an impact on users with Varnish still up and running.

**Comment by jonathanolson** [comment] 2015-06-04 08:47
Can you look at memory usage, or identify and memory leaks? Tomcat will use CPU like crazy when almost full of memory, trying to aggressively garbage collect.

If memory looks like the issue and we can't find any issues, it is possible to take a heap dump of Tomcat while running (although it can't serve requests during that time). That may help identify the issue.

**Comment by aaronsamuel137** [comment] 2015-06-04 14:32
I'll see if I can identify any memory leaks. Looks like the daily memory usage patterns are different after the sim page deploy. Before they were more even:

![screen shot 2015-06-04 at 8 29 11 am](https://cloud.githubusercontent.com/assets/3193912/7986293/f8ffde62-0a93-11e5-9443-af9d5530102b.png)

After the deploy, most days seem to have more of a sawtooth pattern:

![screen shot 2015-06-04 at 8 31 23 am](https://cloud.githubusercontent.com/assets/3193912/7986320/1e695084-0a94-11e5-839c-4f851f56d025.png)

These are two different Wednesdays, one before the deploy and one after.

**Comment by kathy-phet** [comment] 2015-06-05 19:57
Thanks for looking into this comparison -- that was exactly what I was hoping might help you track down the issues. Hopefully you can figure out what might have caused this change. It would be nice to keep it close to that 50% of max heap, as it was before.

**Comment by aaronsamuel137** [comment] 2015-06-08 17:29
It looks like the first week after the deploy the memory usage patterns were more typical of before the deploy but starting last Monday, June 1, then sawtooth pattern has began to emerge. 

I've looked for memory leaks in the code, but this issue is very hard to track down. This is one of the downsides about making so many changes at once, it is hard to identify what change is causing the issue.

Also, Tomcat has seemed to be pretty stable since last Wednesday. It is hard to say for sure what will cause it get sick or sluggish, or when it will happen.

Another issue to discuss with @jonathanolson is the WAR file backups. Are these backups created whenever there is a deploy? It appears that no backups have been created since the new sim pages rollout. The most recent is May 21. I am looking in /data2/website-backup/website-code. I know there is limited disk space in /data2, but I don't think that this is the issue here since we still have 22G and the war files are only around 50M. Perhaps this is related somehow to the new memory issues?

**Comment by jonathanolson** [comment] 2015-06-12 17:06
It definitely looks very different from the original memory issues - there memory only went up. It looks like this could be totally not threatening, if those dips are just garbage collections. Due to the website changes, we could be creating more intermediate objects that get collected.

There's a chance there's some process that is leaking memory and somehow every few hours is resolving the leak, however I think that's fairly unlikely. The only real risk is that heavier traffic would increase how fast the memory is taken up, without making the releases more frequent.

There's probably a 30% chance we could discover any of the issues that would arise by load-testing with Siege or JMeter (as was done before), but it seems for this type of pattern, it's probably related to things like logging on, which is very hard to load test with.

I'm not particularly concerned, and at this point would personally recommend waiting to see if problems start to occur (rather than a very short memory warning) before doing more disruptive and time-consuming diagnostics.

**Comment by ariel-phet** [comment] 2015-06-13 14:48
@aaronsamuel137 and @jonathanolson - would having some larger hard drives make some of these things less of a concern? Hard drives are pretty darn cheap these days, so it seems like if having big drives would give us more of a comfort zone with some of these issues it would be a relatively easy investment.

**Comment by kathy-phet** [comment] 2015-06-14 14:04
Do we have any control over how frequently garbage collection occurs and how much CPU is allotted to it  during this time? You also mention creation of intermediate objects. Would a heap dump show what these are?

**Comment by jonathanolson** [comment] 2015-06-14 17:23
Hard drive space seems unrelated to this issue.

Heap dumps would show intermediate objects generally, and it's possible to set something up so that we can manually trigger garbage collection.

Using this, we would probably be able to determine whether those spikes are garbage collection, or some other freeing of memory.

**Comment by aaronsamuel137** [comment] 2015-06-23 22:45
Tomcat has "gone sick" twice today for around a minute each. I suspect it is related to the installer rip, as this was running during the period when the "going sick" happened. It is the main variable that is different than usual.

New relic shows nothing unusual. The memory usage was not at a particularly high point in the cycle, just somewhere in the middle.

Apache logs don't show a traffic spike. Interestingly, they actually show a traffic dip at the sick times. The following output is requests per minute from 3-4pm.

```bash
grep "23/Jun/2015:16" /usr/local/apache/logs/phet.colorado.edu-access_log | cut -d[ -f2 | cut -d] -f1 | awk -F: '{print $2":"$3}' | sort -nk1 -nk2 | uniq -c | awk '{ if ($1 > 10) print $0}'
    762 16:00
   1087 16:01
   1185 16:02
   1438 16:03
   1391 16:04
   1119 16:05
   1662 16:06
    557 16:07
    239 16:08
    178 16:09   <--- sick around 4:09
   1975 16:10
   1717 16:11
   1545 16:12
   1538 16:13
   1493 16:14
   1586 16:15
   1599 16:16
   1500 16:17
   1584 16:18
   1566 16:19
   1545 16:20
   1385 16:21
   1645 16:22
   1836 16:23
   1220 16:24
   1167 16:25
    674 16:26
    899 16:27
    772 16:28
    900 16:29
   1206 16:30
   1235 16:31
    986 16:32
    932 16:33
    678 16:34
    897 16:35
    960 16:36
    658 16:37
    765 16:38
    654 16:39
    612 16:40
    635 16:41
```

**Comment by aaronsamuel137** [comment] 2015-07-06 15:16
I am starting to get suspicious of some data we are getting from new-relic. The saw-tooth memory pattern that seemed to occur after the new sim pages deploy may have been happening before too.

For instance, when I look back at June 2 in New Relic now, the saw tooth pattern is not there:

<img width="737" alt="screen shot 2015-07-06 at 9 12 28 am" src="https://cloud.githubusercontent.com/assets/3193912/8525645/6a438148-23bf-11e5-8fbe-21f706084760.png">

Whereas this same time period showed the saw tooth pattern when I looked at it before (see my comment https://github.com/phetsims/website/issues/220#issuecomment-108915926). It might be that much of the granularity of the data is lost as we go back in time?

I will email New Relic and see what I can find out about this.

**Comment by aaronsamuel137** [comment] 2015-07-06 16:41
On Friday 7/3, figaro "went sick" for about an hour and a half until I restarted it. The site appeared to be up and running with Varnish, but logging in, etc. was not working.

New Relic shows that the old gen memory space was full, but the GC wasn't able to collect anything.

Discussed with @jonathanolson on 7/6/15. We suspect the cause might lie with the custom caches that the website uses. I will investigate this. If I don't find anything, a heap dump might be a good next step.

**Comment by aaronsamuel137** [comment] 2015-07-07 03:17
As suspected by @jonathanolson and I, clearing the website caches and then triggering a GC frees up memory very quickly. I cleared the caches and triggered a GC around 9:05pm:

<img width="712" alt="screen shot 2015-07-06 at 9 11 17 pm" src="https://cloud.githubusercontent.com/assets/3193912/8538010/b1053c20-2423-11e5-9f7c-74373dc90ded.png">

This strongly suggests that one or more of the website caches is responsible for the memory leak. It seems likely that whatever memory issue is present was not caused by the new sim pages deploy, but perhaps slightly exacerbated by it.

**Comment by jonathanolson** [comment] 2015-07-07 03:26
Any thoughts on which cache is the culprit? We can clear each one individually to test, if the numbers from the memory report don't reveal what's going on.

**Comment by aaronsamuel137** [comment] 2015-07-07 03:41
Not sure, I had the same thought that we could clear each one individually to find out. Perhaps we can talk tomorrow so I can get a clear sense from you which caches correlate with the numbers on the memory stats page.

Here are the numbers right before the cache clearing and GC:

```
PhetWicketApplication.translations: 36

ImageCache.imageMap: 368

PhetLocalizer.cache: 57716

PanelCache.cache: 6929

SimulationCache.preferredSims: 37

SimulationCache.fullSortedLocalizedMap: 37

Autocomplete tries: 2817

HibernateEventListener.listenerMap: 33399

CategoryChangeHandler.listeners: 512

InitialSubscribeCount.ipAttempts: 0

InitialSubscribeCount.emailAttempts: 0

ComponentThreadStatusPanel.threadMap: 0

ResetPasswordRequestPanel.attempts: 11

Hibernate Event classes:
edu.colorado.phet.website.data.Project: 6874edu.colorado.phet.website.data.TranslatedString: 7045edu.colorado.phet.website.data.Category: 2edu.colorado.phet.website.data.Simulation: 6874edu.colorado.phet.website.data.LocalizedSimulation: 6873edu.colorado.phet.website.data.contribution.ContributionComment: 1edu.colorado.phet.website.data.contribution.ContributionNomination: 1edu.colorado.phet.website.data.contribution.Contribution: 5729

Hibernate listener classes:
edu.colorado.phet.website.notification.NotificationHandler$3: 1edu.colorado.phet.website.cache.SimulationCache$1: 3edu.colorado.phet.website.translation.entities.NavigationEntity$3: 2edu.colorado.phet.website.cache.ImageCache$1: 2edu.colorado.phet.website.cache.EventDependency$3: 7045edu.colorado.phet.website.notification.NotificationHandler$2: 1edu.colorado.phet.website.panels.simulation.SimulationMainPanel$18$1: 5728edu.colorado.phet.website.cache.EventDependency$1: 20616edu.colorado.phet.website.notification.NotificationHandler$1: 1

CategoryChangeHandler listeners:
edu.colorado.phet.website.panels.simulation.SimulationListViewPanel$2$1: 511edu.colorado.phet.website.menu.NavMenu$2: 1
```

**Comment by aaronsamuel137** [comment] 2015-07-07 15:23
I tried just clearing the panel cache and running the GC and found similar behavior:

<img width="733" alt="screen shot 2015-07-07 at 9 22 32 am" src="https://cloud.githubusercontent.com/assets/3193912/8549754/bf002e28-2489-11e5-8fb3-59ccb5d26d08.png">


The seems like a good place to start. I do want to run another test just trying GC by itself to verify that the same thing won't happen. Last time I tried to trigger a GC not much occurred.

**Comment by aaronsamuel137** [comment] 2015-07-14 22:56
After limited this size of the panel cache, the memory trends on figaro seem to have changed dramatically:

<img width="725" alt="screen shot 2015-07-14 at 4 53 36 pm" src="https://cloud.githubusercontent.com/assets/3193912/8687014/03a634d6-2a49-11e5-8e1d-6d5f45f28303.png">

Overall, it seems like less memory usage in general, and not as much of a sawtooth pattern. This could potentially solve our memory issues!

**Comment by aaronsamuel137** [comment] 2015-08-13 17:15
Haven't seen any issues since shrinking the panel cache. Closing this for now. We can reopen if anything else needs attention.

**Closed by aaronsamuel137** 2015-08-13 17:15 UTC
Labels: High Priority, Server side
