### ISSUE TITLE
Can't change email associated with an account

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website#167] opened 2015-05-12 15:53 UTC
So I'm trying to change the email I have on an account I already registered, and the only clear way for me to do this is to edit my profile, then type in the new email, and click "Update". But alas, this does not work, and going back to my profile it still has my old email address. Is it currently not a feature to switch emails? Making a whole new account seems laborious.

Mac OSX 10.10.1, Chrome 42.

**Comment by ariel-phet** [comment] 2015-05-12 15:58
@aaronsamuel137 - this seem likes a good question

**Comment by patricialoeblein** [comment] 2015-05-12 16:09
This would be helpful for teachers and faculty because when they change positions, they often change email. Many like me,  use a professional email for work related sites like education ones.

**Comment by aaronsamuel137** [comment] 2015-05-12 16:19
This is currently not possible on either the main site or phet-dev. I can look into adding this functionality if that seems important.

**Comment by ariel-phet** [comment] 2015-05-12 18:42
It would be good to investigate this functionality, but it can wait until after the sim pages rollout

**Comment by aaronsamuel137** [comment] 2015-05-30 17:12
Any thoughts about the UI for this? Should it just be another field on the edit profile page? Or we could have another link next to "Change password" - something like "Change email address", which goes to a simple form similar to the change password form. Whatever we decide, we'll need an extra step to send a confirmation email.

Another complication here is the "contact email" field for activities. The contact email does not have to be the same as the activity creator's email, so it is not obvious whether or not we should update this for all of the user's activities. Perhaps we should update this field if it is the same as the email they are changing?

Thoughts on this @ariel-phet and @amanda-phet?

**Comment by amanda-phet** [comment] 2015-06-01 16:29
I like the idea of adding a "Change email address" link above or next to the "change password" link. 

I would ignore the contact email field for activities, since teacher may intentionally use a different email there.

**Comment by aaronsamuel137** [comment] 2015-06-02 22:01
I have attempted an implementation of this on phet-dev. @ariel-phet and @amanda-phet, please review when you have time. You'll find a link to change email at the bottom of the profile edit page.

Once the UX details of this are fleshed out, we'll want to do some pretty thorough testing before deploying - including testing of creating new accounts and editing accounts. This change has touched a fair amount of code.

**Comment by aaronsamuel137** [comment] 2015-06-02 22:12
There is a known issue right now where the once you click the confirm link you'll still see the old email address you go to another page.

For now, it would be good to get feedback about the layout of the pages, the wording of the confirm emails, etc.

**Comment by ariel-phet** [comment] 2015-06-02 22:26
One things we were wondering looking at this flow is once you click "edit email" could your current email address just be filled in? You are already signed into the site at this point and your email address is displayed in the top right of the banner, so was there a rationale for having you fill in your email address?

**Comment by aaronsamuel137** [comment] 2015-06-02 22:36
I thought about that. It seems reasonable to me. I did it this way based on a vague memory of other sites doing something similar.

But if we are going to pre-fill it in, we might as well just get rid of that top field all together and just have one field for new email? Or do you see some reason to keep it even if it is pre-filled? Right now you can't access that page unless you are signed in.

**Comment by amanda-phet** [comment] 2015-06-03 21:31
If we can get rid of it then I think that would make the most sense. We weren't sure if it was there for verification or some other reason that you had in mind.

**Comment by aaronsamuel137** [comment] 2015-06-05 03:28
I've updated the from to just have the one input.

The issue of having the wrong email show up initially when you click on the confirm link is difficult to fix. Because going to the link is what actually changes your email, when the page is first constructed the old email is still in the database. The next page you visit will show the updated email. Does this seem like an issue or can we leave it as is? Any other changes you see useful here?

Assigning to @ariel-phet or @amanda-phet for review.

**Comment by amanda-phet** [comment] 2015-06-08 15:06
What you are saying makes perfect sense. The email isn't changed until I click the link in the confirmation email. After I log in after that point, the email address in the top banner should be updated. 

After I change my email I am having trouble logging in with the new email. It's saying an invalid username and/or password has been entered.

**Comment by aaronsamuel137** [comment] 2015-06-08 15:24
Hmm not sure what is going on here. It seems to be working for me when I test it. Does your old email still work or neither of them?

**Comment by amanda-phet** [comment] 2015-06-08 16:24
Neither email is working. I've also tried another browser.

**Comment by aaronsamuel137** [comment] 2015-06-08 16:29
Does the new email work if you try and reset your password? Also, can you send me the new email address so I can check if it is in the database? Feel free to email me if you don't want it on github.

Are you up for testing this too @ariel-phet or @phet-steele? I can't reproduce a case where this doesn't work for me, so it would be good to do some more testing

**Comment by amanda-phet** [comment] 2015-06-08 16:46
Resetting my password worked, but I shouldn't have to do that to make my new email work. I have changed the email back, and the new one does not work, but the old one still does (which is different from last time). I'll keep trying and see if it just has a delay before it works.

**Comment by aaronsamuel137** [comment] 2015-06-08 16:55
Ah I think there is a bug when trying with an admin email. I was testing with non team member emails before.

**Comment by aaronsamuel137** [comment] 2015-06-08 17:03
Looks like there are a few bugs here, I'll let you know when I have addressed them.

**Comment by aaronsamuel137** [comment] 2015-06-08 18:02
OK see if it works for you now @amanda-phet. Thanks!

**Comment by amanda-phet** [comment] 2015-06-08 19:38
It still seems to only work if I also click "forgot password."

**Comment by aaronsamuel137** [comment] 2015-06-09 02:14
What do you mean also click forgot password? Are you talking about the "forgot password" link on the sign in popup? I am unclear of what you mean by this.

**Comment by amanda-phet** [comment] 2015-06-09 15:09
Yes, I must click the "forgot password" link on the sign in dialog in order to reset my password. I thought that was what you suggested, but I realize now you probably intended for me to click the link on the edit profile page instead.

**Comment by aaronsamuel137** [comment] 2015-06-09 15:13
I've addressed some issues and just want you to see if the "change email" link and process works for you now. You shouldn't need to reset your password at this point - if you do that is a bug.

**Comment by aaronsamuel137** [comment] 2015-06-10 19:07
Can you review this on phet-dev @ariel-phet? See if the bugs are fixed and if the general UX and wording of emails seems good.

Assigning to @ariel-phet.

**Comment by amanda-phet** [comment] 2015-06-10 19:18
Sorry for not responding yesterday. It works perfectly for me now.

**Comment by aaronsamuel137** [comment] 2015-06-10 22:16
Great! Do you think it's ready to deploy to the live site? If so, I think we should have @phet-steele do some more testing beforehand - including testing of creating new accounts, editing, profiles in general, etc. Want to be sure no other errors crept in since this touches a fair amount of code.

**Comment by amanda-phet** [comment] 2015-06-12 17:02
Yes please have @phet-steele test it!

**Comment by phet-steele** [comment] 2015-06-12 18:25
Well here's whats happening with regards to email changing, step by step.
1. I registered using one email, let's call it email A.
2. Signed in with email A, went to edit my profile, scrolled down and clicked the link the change my email.
3. Typed in email B. Clicked the link in the sent email to confirm the change and it directed me to a new tab of phet-dev.
4. I disregarded the new tab and went back to the original tab and did multiple hard refreshes and navigations, but the email displayed in the top right continued to display email A instead of email B.
5. Clicked on "Share my Activities" and the auto-filled email entered on the form was still email A.
6. I went ahead and signed out of email A.
7. Signing in with email B did not work.
8. I clicked on the "Forgot Password?" link on the sign in pop up.
9. I decided to send a password change request to both email A and B.
10. I first changed the password for email B. Signing in with email B now works.
11. I then changed the password for email A, using the link in the email sent to email A.
12. I was able to sign in with email A after doing this.
13. Signing out of email A then back into email B also worked. So yes, I can sign in with either email.
14. Editing the profile on one doesn't change the info on the other, so do I have two separate accounts now?

**Comment by phet-steele** [comment] 2015-06-12 18:48
As another thing, the old email is still shown on this page after following the link to change the email: 
![wrong email](https://cloud.githubusercontent.com/assets/5863899/8137519/35f1260a-1101-11e5-8e8f-97172f2d4b9f.PNG)

steele.phet@gmail.com was the old email

**Comment by amanda-phet** [comment] 2015-06-12 18:50
It is known that the old email still appears in the banner until you sign out and sign back in again.

**Comment by phet-steele** [comment] 2015-06-12 18:51
Okay. @aaronsamuel137 also confirmed I do in fact have multiple accounts now.

**Comment by amanda-phet** [comment] 2015-06-16 18:21
I just tested this again and it appears to be broken again... after changing my email, neither the new or old email will work until I click "forgot password" and reset my password. Then I can sign in.

**Comment by arouinfar** [comment] 2015-06-16 18:21
I also experienced the same issue described by @amanda-phet.

**Comment by aaronsamuel137** [comment] 2015-06-16 21:01
OK thanks for testing. This is a mysterious issue that I do not understand yet. It still always works whenever I try it, so there must be something inconsistent happening. I'll add some more log statements to see if it gives any clues.

**Comment by aaronsamuel137** [comment] 2015-06-18 21:17
I think I have figured out the issue here. Basically, the password hashes in the database use the email as a salt - which makes changing emails much more complicated than it would have been otherwise.

**Comment by aaronsamuel137** [comment] 2015-06-19 15:12
I think I have fixed this. Now you are required to enter your password when you change your email as well as the new email. This is necessary because the way passwords are hashed and stored in the database depends on the email address.

The reason is was working for me before is that the hashing only depends on the first 5 characters of the email address, which is the same in all of my email addresses.

Please test again when you get a chance @phet-steele or @amanda-phet.

**Comment by phet-steele** [comment] 2015-06-19 19:16
If everything is done normally, it all works great for me! There's a strange use case of me using a computer in conjunction with my phone (or possibly just any second device) where I can continue to use the website on my computer with my old email, until I sign out. Aside from that, this works as intended for me now.

**Comment by amanda-phet** [comment] 2015-06-19 19:19
It is working for me and @arouinfar just fine now!

**Comment by phet-steele** [comment] 2015-06-19 19:59
@ariel-phet, I'm never one to say testing is done, but if you don't think the use case I described in my previous comment needs to be addressed, then go ahead and close this.

**Comment by aaronsamuel137** [comment] 2015-06-19 20:12
I am planning on deploying this to the main site on the next (probably early next week) unless I hear otherwise. I will close when it is deployed.

**Comment by ariel-phet** [comment] 2015-06-19 20:38
@phet-steele - Thanks for testing and finding that usecase, I don't think we need to address that case, but good to have it identified.

@aaronsamuel137 - yes, please close when deployed.

**Comment by aaronsamuel137** [comment] 2015-06-23 01:44
Deployed. Closing

**Comment by aaronsamuel137** [comment] 2015-07-23 16:24
Discussed at 7/23/15 status meeting. We eventually want to make all emails case insensitive, and right not there are ~3000 users whose emails are not all lowercase already.

The best solution seems to be to update users' emails when they log in. That way, we will have their password in plain text. We will either need to try both versions of the email or add another column to the the database. I'm leaning toward the first option personally.

@zepumph, feel free to tackle this if you have time before you leave.

**Comment by ariel-phet** [comment] 2015-11-06 19:22
Reassigning to @mattpen - this will likely take some direction from @jonathanolson or @aaronsamuel137 if he has some time.

**Comment by aaronsamuel137** [comment] 2015-11-06 19:33
Might be a good one to tackle together before I leave. Give me a call about this next week @mattpen.

**Comment by mattpen** [comment] 2015-12-30 20:22
@jonathanolson - Do we need to convert all the emails to lowercase before making the sign-on case insensitive?  It looks like Aaron's fix earlier just made all emails lowercase, not case-insensitive.  Wouldn't it be easier to handle this through the salt rather than at the email prompt?

I tested the above commit on the VM and it seems to be working with a handful of accounts I created.  Can you please review the commit when you have a chance?

**Comment by mattpen** [comment] 2016-01-29 19:14
Discussed with @oliver-phet on 1/28/2016.  We had a user who had two accounts created with identical emails with different case structure.  Because the emails looked the same in a case-insensitive search, the user could not logon.

We decided to increase the priority of this issue.  We decided that the email address in all user activity should be checked in a case-insensitive format (logon, registration, email change, password reset, etc.), but that we should actually store the user entered case-sensitive email address for use in mailing.

**Comment by mattpen** [comment] 2016-02-11 23:51
@oliver-phet - Case-insensitive login should be live now on phet-dev.  I also cleaned up the duplicate accounts in #377, and it is not possible to create duplicate accounts with the new procedures.  I've opened a task to test the changes - phetsims/tasks#512

**Comment by mattpen** [comment] 2016-02-18 07:07
The changes were deployed to figaro tonight.  Users now have the ability to change their email and login is case-insensitive ( we are retaining the user-provided case for outgoing mail ).

**Closed by mattpen** 2016-02-18 07:07 UTC
Labels: dev:enhancement, type:bug, website:user-accounts
