### ISSUE TITLE
Create page with WebGL enabling instructions

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website#50] opened 2014-12-11 18:58 UTC
Here is the Google doc link. It sounds like for now, we can just either embed this or turn it into text. (Translation not high-priority)
https://docs.google.com/document/d/1hHJqbvqiC608Xoz9qo8YH85GTsZIXEs2ubeEz9b3LJs/edit?usp=sharing

**Comment by ariel-phet** [comment] 2015-02-04 17:30
Duplicate of #26, closing

**Closed by ariel-phet** 2015-02-04 17:30 UTC
Labels: duplicate
